package com.noisefit_commans.interfaces

import com.noisefit_commans.models.*

sealed class QueryCallback {

    class BatteryAlertObtained(val batteryLevel: Int) : QueryCallback()
    class BatteryDataObtained(val batteryData: BatteryData) : QueryCallback()
    class FirmwareVersionObtained(val deviceFirmware: DeviceFirmware) : QueryCallback()
    object ClickCameraImage : QueryCallback()


    class CloseCameraShutterActivity(val finish: Boolean) : QueryCallback()
    class UpdateCallStatus(val status: Boolean, val forceCallDisconnect: Boolean = false) :
        QueryCallback()

    class FirmwareUpgradeAvailable(val deviceFirmware: DeviceFirmware) : QueryCallback()
    class FirmwareUpgradeAvailableNew(deviceFirmware: DeviceFirmware) : QueryCallback()
    class UserInfoReceived(userInfo: UserInfo) : QueryCallback()
    class FindMyPhoneSwitchObtained(val switchSetting: SwitchSetting) : QueryCallback()
    class LanguageReceived(val language: Language) : QueryCallback()
    class AlarmsObtained(val alarmsList: AlarmsList) : QueryCallback()
    class WatchFacesObtained(val watchFace: List<WatchFace>) : QueryCallback()
    class DoNotDisturbObtained(val doNotDisturb: DoNotDisturb) : QueryCallback()
    class AppListObtained(val appList: List<Widget>) : QueryCallback()
    class MenstrualSettingsObtained(val menstrualData: MenstrualData) : QueryCallback()
    class DeviceUnitsObtained(units: DeviceUnits) : QueryCallback()
    class SedentaryDataObtained(val sedentaryData: SedentaryData) : QueryCallback()
    class StartDayOfTheWeek(startDayOfWeek: StartDayOfWeek) : QueryCallback()
    class MusicControl(val switchSetting: SwitchSetting) : QueryCallback()
    class CameraSwitchObtained(val switchSetting: SwitchSetting) : QueryCallback()
    class CallAlert(switchSetting: SwitchSetting) : QueryCallback()
    class UserGoalsObtained(goals: UserGoals) : QueryCallback()
    class WeatherSwitchStatus(switchSetting: SwitchSetting) : QueryCallback()
    class WristLiftGestureObtained(val wristLiftGesture: WristLiftGesture) : QueryCallback()
    class BrightnessLevelObtained(val level: Int) : QueryCallback()
    class VibrationIntensityObtained(val vibrationIntensity: VibrationIntensity) : QueryCallback()
    class ScreenAwakeIntervalObtained(val interval: Int) : QueryCallback()
    class HeartRateIntervalObtained(val interval: HeartRateInterval) : QueryCallback()
    class Spo2SettingsObtained(val spo2Data: Spo2Data) : QueryCallback()
    class AutoSleepObtained(val autoSleep: AutoSleep) : QueryCallback()
    class WatchFaceLayoutObtained(watchFaceLayout: WatchFaceLayout) : QueryCallback()
    class SwitchSettingObtained(switchSetting: SwitchSetting) : QueryCallback()
    class CustomReplyObtained(val customReplyData: CustomReplyData) : QueryCallback()
    class GetHandWashing(val handWashing: HandWashing) : QueryCallback()
    class HeartRateAlertDataObtained(val heartRateAlert: HeartRateAlert) : QueryCallback()
    class RemindersObtained(val reminderList: ReminderList) : QueryCallback()
    class Error(colorFitError: ColorfitError) : QueryCallback()
    class ActivityRecognise(val switchSetting: SwitchSetting) : QueryCallback()
    class DrinkWaterDataObtained(val sedentaryData: SedentaryData) : QueryCallback()
    class MealDataObtained(val sedentaryData: SedentaryData) : QueryCallback()
    class MedicineDataObtained(val sedentaryData: SedentaryData) : QueryCallback()
    class StressParamObtained(val sedentaryData: SedentaryData) : QueryCallback()
    class WalkReminderDataObtained(val walkReminderData: WalkReminderData) : QueryCallback()
    class SportModeInfoObtained(val sportsModeList: SportsModeList?) : QueryCallback()
    class FirmwareLogObtained(val fileName: String) : QueryCallback()
    class WorldClockDataObtained(val worldClocks: WorldClockList) : QueryCallback()
    class WatchPasswordObtained(val watchPassword: WatchPassword) : QueryCallback()
    class StockListDataObtained(val stockSymbolList: StockSymbolList) : QueryCallback()
    class SyncStock() : QueryCallback()
    class QuickEyeMovementSwitchObtained(val switchSetting: SwitchSetting) : QueryCallback()
    class OnMusicEventChanged(val event: String) : QueryCallback()
    class Default() : QueryCallback()
    class MuteDevice() : QueryCallback()
    class BodyTempUnit(var unit: Units) : QueryCallback()
    class BluetoothCallStatus(val status: Boolean) : QueryCallback()
    class ContactListObtained(var contactData: List<Contact>) : QueryCallback()
    class DeleteStock(val success: Boolean) : QueryCallback()
    class BleCallingSwitchObtained(val success: Boolean) : QueryCallback()
    class SportWidgetSortList(val sportWidgetSortList: ArrayList<Widget>) : QueryCallback()
    class WidgetSortListObtained(val widgetList: List<Widget>) : QueryCallback()
    class OpenFindMyPhoneActivity(val isRinging: Boolean) : QueryCallback()
    class OpenCameraActivity(val close: Boolean) : QueryCallback()
    class UPIQRCodeObtained(var uPIQRCodes: List<UPIQRCode>?) : QueryCallback()
    class AgpsRequestState(val shouldUpdate: Boolean) : QueryCallback()
    class SOSContactObtained(var sosContact: SOSContact) : QueryCallback()

    class SleepReminderObtained(var sleepReminder: SleepReminder) : QueryCallback()
    class UpdateFirmwareLogStatus(var fwLogStatus: Int) : QueryCallback()
}