// build.gradle.kts.kts.kts.kts.kts for android libraries that contain UI

apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-kapt'
apply plugin: 'dagger.hilt.android.plugin'
apply plugin: 'kotlin-parcelize'

android {
    compileSdkVersion Android.compileSdk
//    buildToolsVersion Android.buildTools

    defaultConfig {
        minSdkVersion Android.minSdk
        targetSdkVersion Android.targetSdk
        versionCode Android.versionCode
        versionName Android.versionName
        multiDexEnabled = true
//        testInstrumentationRunner = AndroidXTest.instrumentationRunner
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_11
        targetCompatibility = JavaVersion.VERSION_11
    }
    kotlinOptions {
        jvmTarget = Java.java
    }
//    buildFeatures {
//        compose true
//    }
//    composeOptions {
//        kotlinCompilerExtensionVersion Compose.composeVersion
//        kotlinCompilerVersion Kotlin.version
//    }

    sourceSets {
        main {
            jniLibs.srcDirs = ['libs']
        }
    }
    packagingOptions {
        exclude("META-INF/AL2.0")
        exclude("META-INF/LGPL2.1")
    }
}

dependencies{

    implementation libs.timber
    implementation libs.androidx.localbroadcastmanager
    implementation libs.play.service.location
    implementation libs.dagger.hilt.android
    kapt libs.dagger.hilt.compiler

    implementation libs.androidx.core.ktx
    implementation libs.kotlin.stdlib
    implementation libs.gson


}
