pluginManagement {
    repositories {
        gradlePluginPortal()
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' }


    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.PREFER_SETTINGS)
    repositories {
        gradlePluginPortal()
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' }


        versionCatalogs {
            create("moengage"){
                from("com.moengage:android-dependency-catalog:4.3.0")
            }
        }
    }
}
rootProject.name = "LunaRing"
include ':app'
include ':commons'
include ':noisefit_libraries_zh'
include ':MPChartLib'
include(":noisefit_zh_sdk")


include ':timePickerSlider'
