[versions]
androidDecoviewCharting = "v1.2"
androidJoda = "2.13.1"
appcompat = "1.7.1"
blurview = "version-2.0.3"
carouselView = "1.1.1"
coilComposeVersion = "2.5.0"
constraintlayoutCompose = "1.1.1"
core = "4.6.2"
curlloggerinterceptor = "0.1"
desugar_jdk_libs = "2.1.5"
elvishewXlog = "1.11.1"
agp = "8.11.0"
flexbox = "3.0.0"
gradle = "8.11.0"
freshchatAndroid = "6.4.4"
jjwtVersion = "0.12.6"
junit = "4.13.2"
kotlin = "2.2.0"
coreKtx = "1.16.0"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
kotlinBom = "2.0.21"
lifecycleRuntimeKtx = "2.9.1"
navigationFragmentKtx = "2.9.1"
navigationUiKtx = "2.9.1"
anrwatchdog = "1.4.0"
oksse = "0.9.0"
pagingCommonKtx = "3.3.6"
sdpAndroid = "1.1.1"
shimmertextviewVersion = "1.0.1"
shimmerVersion = "0.5.0"
timber = "5.0.1"
swipe-refresh-library-core = "1.7.2.4"
truth = "1.4.4"
ucrop = "2.2.10"
utilcodex = "1.31.1"
tankery-circularSeekBar = "1.4.2"
room = "2.7.2"
retrofit = "3.0.0"
retrofit-logging-interceptor = "5.0.0"
protobuf = "3.22.3"
play-service-fitness = "21.2.0"
play-service-maps = "19.2.0"
play-service-location = "21.3.0"
play-service-auth = "21.3.0"
google-services = "4.4.3"
google-services-phone-api = "18.2.0"
goodiebag-pinview = "1.4"
maps-utils = "3.14.0"
lottie = "6.6.7"
coroutines = "1.10.2"
konfetti-xml = "2.0.5"
konfetti-core = "2.0.5"
dagger-hilt = "2.56.2"
hilt-compiler = "1.2.0"
gson = "2.13.1"
material = "1.12.0"
glide = "4.16.0"
collapsingtoolbarlayout = "1.5.0"
firebase-bom = "33.16.0"
fb-sdk = "18.0.3"
exoplayer = "2.19.1"
androidx-lifecycle = "2.9.1"
multidex = "2.0.1"
localbroadcastmanager = "1.1.0"
vectordrawable = "1.2.0"
camerax = "1.4.2"
camerax-view = "1.4.2"
lifecycle-extensions = "2.2.0"
hilt-work = "1.2.0"
calendar-view = "2.7.0"
work-runtime-ktx = "2.10.2"
concurrent-futures-ktx = "1.2.0"
fragment-ktx = "1.8.8"
constraintlayout = "2.2.1"
viewpager2 = "1.1.0"
legacy-support-v4 = "1.0.0"
lifecycle-process = "2.9.1"
paging-runtime = "3.3.6"
protobuf-gradle-plugin = "0.9.5"
navigation-safe-args-gradle-plugin = "2.9.1"
hilt-android-gradle-plugin = "2.56.2"
firebase-crashlytics-gradle = "3.0.4"
reviewKtx = "2.0.2"
activityComposeVersion = "1.10.1"
composeBomVersion = "2025.06.01"


[libraries]
android-decoview-charting = { module = "com.github.bmarrdev:android-DecoView-charting", version.ref = "androidDecoviewCharting" }
android-joda = { module = "net.danlew:android.joda", version.ref = "androidJoda" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-constraintlayout-compose = { module = "androidx.constraintlayout:constraintlayout-compose", version.ref = "constraintlayoutCompose" }
androidx-hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hilt-compiler" }
androidx-paging-common-ktx = { module = "androidx.paging:paging-common-ktx", version.ref = "pagingCommonKtx" }
anrwatchdog = { group = "com.github.anrwatchdog", name = "anrwatchdog", version.ref = "anrwatchdog" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
blurview = { module = "com.github.Dimezis:BlurView", version.ref = "blurview" }
carousel-view = { module = "com.github.alirezat775:carousel-view", version.ref = "carouselView" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coilComposeVersion" }
core = { module = "io.noties.markwon:core", version.ref = "core" }
curlloggerinterceptor = { module = "com.github.grapesnberries:curlloggerinterceptor", version.ref = "curlloggerinterceptor" }
desugar_jdk_libs = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar_jdk_libs" }
flexbox = { module = "com.google.android.flexbox:flexbox", version.ref = "flexbox" }
freshchat-android = { module = "com.github.freshworks:freshchat-android", version.ref = "freshchatAndroid" }
google-firebase-config-ktx = { module = "com.google.firebase:firebase-config-ktx" }
gradle = { module = "com.android.tools.build:gradle", version.ref = "gradle" }
jjwt = { module = "io.jsonwebtoken:jjwt", version.ref = "jjwtVersion" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
elvishew-xlog = { group = "com.elvishew", name = "xlog", version.ref = "elvishewXlog" }
junit = { module = "junit:junit", version.ref = "junit" }
kotlin-bom = { module = "org.jetbrains.kotlin:kotlin-bom", version.ref = "kotlinBom" }
mindinventory-shimmertextview = { module = "com.github.Mindinventory:ShimmerTextView", version.ref = "shimmertextviewVersion" }
oksse = { module = "com.github.heremaps:oksse", version.ref = "oksse" }
sdp-android = { module = "com.intuit.sdp:sdp-android", version.ref = "sdpAndroid" }
shimmer = { module = "com.facebook.shimmer:shimmer", version.ref = "shimmerVersion" }
timber = { group = "com.jakewharton.timber", name = "timber", version.ref = "timber" }
swipe-refresh-library-core = { group = "com.github.dkzwm", name = "srl-core", version.ref = "swipe-refresh-library-core" }
truth = { module = "com.google.truth:truth", version.ref = "truth" }
ucrop = { module = "com.github.yalantis:ucrop", version.ref = "ucrop" }
utilcodex = { module = "com.blankj:utilcodex", version.ref = "utilcodex" }
tankery-circularSeekBar = { group = "me.tankery.lib", name = "circularSeekBar", version.ref = "tankery-circularSeekBar" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
retrofit-logging-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "retrofit-logging-interceptor" }
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofit-converter-gson = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofit" }
protobuf = { group = "com.google.protobuf", name = "protobuf-java", version.ref = "protobuf" }
play-service-fitness = { group = "com.google.android.gms", name = "play-services-fitness", version.ref = "play-service-fitness" }
play-service-maps = { group = "com.google.android.gms", name = "play-services-maps", version.ref = "play-service-maps" }
play-service-location = { group = "com.google.android.gms", name = "play-services-location", version.ref = "play-service-location" }
play-service-auth = { group = "com.google.android.gms", name = "play-services-auth", version.ref = "play-service-auth" }
google-service = { group = "com.google.gms", name = "google-services", version.ref = "google-services" }
play-service-auth-api = { group = "com.google.android.gms", name = "play-services-auth-api-phone", version.ref = "google-services-phone-api" }
goodiebag-pinview = { group = "com.github.GoodieBag", name = "Pinview", version.ref = "goodiebag-pinview" }
maps-utils = { group = "com.google.maps.android", name = "android-maps-utils", version.ref = "maps-utils" }
lottie = { group = "com.airbnb.android", name = "lottie", version.ref = "lottie" }
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin" }
konfetti-xml = { group = "nl.dionsegijn", name = "konfetti-xml", version.ref = "konfetti-xml" }
konfetti-core = { group = "nl.dionsegijn", name = "konfetti-core", version.ref = "konfetti-core" }
dagger-hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "dagger-hilt" }
dagger-hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "dagger-hilt" }
hilt-compiler = { group = "androidx.hilt", name = "hilt-compiler", version.ref = "hilt-compiler" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
android-material = { group = "com.google.android.material", name = "material", version.ref = "material" }
material-collapsingtoolbarlayout = { group = "com.hendraanggrian.material", name = "collapsingtoolbarlayout-subtitle", version.ref = "collapsingtoolbarlayout" }
glide = { group = "com.github.bumptech.glide", name = "glide", version.ref = "glide" }
firebase-config-ktx = { group = "com.google.firebase", name = "firebase-config-ktx" }
firebase-analytics-ktx = { group = "com.google.firebase", name = "firebase-analytics-ktx" }
firebase-crashlytics-ktx = { group = "com.google.firebase", name = "firebase-crashlytics-ktx"}
firebase-messaging-ktx = { group = "com.google.firebase", name = "firebase-messaging-ktx"}
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebase-bom" }
facebook-android-sdk = { group = "com.facebook.android", name = "facebook-android-sdk", version.ref = "fb-sdk" }
exoplayer-core = { group = "com.google.android.exoplayer", name = "exoplayer-core", version.ref = "exoplayer" }
exoplayer-dash = { group = "com.google.android.exoplayer", name = "exoplayer-dash", version.ref = "exoplayer" }
exoplayer-ui = { group = "com.google.android.exoplayer", name = "exoplayer-ui", version.ref = "exoplayer" }
androidx-lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-livedata-ktx = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "androidx-lifecycle" }
androidx-multidex = { group = "androidx.multidex", name = "multidex", version.ref = "multidex" }
androidx-localbroadcastmanager = { group = "androidx.localbroadcastmanager", name = "localbroadcastmanager", version.ref = "localbroadcastmanager" }
androidx-vectordrawable = { group = "androidx.vectordrawable", name = "vectordrawable", version.ref = "vectordrawable" }
androidx-navigation-fragment-ktx = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigationFragmentKtx" }
androidx-navigation-ui-ktx = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigationUiKtx" }
androidx-camera = { group = "androidx.camera", name = "camera-camera2", version.ref = "camerax" }
androidx-camera-lifestyle = { group = "androidx.camera", name = "camera-lifecycle", version.ref = "camerax" }
androidx-camera-view = { group = "androidx.camera", name = "camera-view", version.ref = "camerax-view" }
androidx-lifecycle-extensions = { group = "androidx.lifecycle", name = "lifecycle-extensions", version.ref = "lifecycle-extensions" }
androidx-hilt-work = { group = "androidx.hilt", name = "hilt-work", version.ref = "hilt-work" }
androidx-work-runtime-ktx = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "work-runtime-ktx" }
androidx-concurrent-futures-ktx = { group = "androidx.concurrent", name = "concurrent-futures-ktx", version.ref = "concurrent-futures-ktx" }
androidx-fragment-ktx = { group = "androidx.fragment", name = "fragment-ktx", version.ref = "fragment-ktx" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
androidx-viewpager2 = { group = "androidx.viewpager2", name = "viewpager2", version.ref = "viewpager2" }
androidx-legacy-support = { group = "androidx.legacy", name = "legacy-support-v4", version.ref = "legacy-support-v4" }
androidx-lifecycle-process = { group = "androidx.lifecycle", name = "lifecycle-process", version.ref = "lifecycle-process" }
androidx-paging-runtime = { group = "androidx.paging", name = "paging-runtime", version.ref = "paging-runtime" }
googleProtobufGradlePlugin = { group = "com.google.protobuf", name = "protobuf-gradle-plugin", version.ref = "protobuf-gradle-plugin" }
androidxNavigationSafeArgsGradlePlugin = { group = "androidx.navigation", name = "navigation-safe-args-gradle-plugin", version.ref = "navigation-safe-args-gradle-plugin" }
googleDaggerHiltAndroidGradlePlugin = { group = "com.google.dagger", name = "hilt-android-gradle-plugin", version.ref = "hilt-android-gradle-plugin" }
googleFirebaseCrashlyticsGradle = { group = "com.google.firebase", name = "firebase-crashlytics-gradle", version.ref = "firebase-crashlytics-gradle" }
review-ktx = { group = "com.google.android.play", name = "review-ktx", version.ref = "reviewKtx" }
calendarView = { module = "com.kizitonwose.calendar:view", version.ref = "calendar-view" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityComposeVersion" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBomVersion" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
jetbrainsKotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }



