package com.noisefit_commans.utils

object InsiderAppEvents {

    //Actual Insider Event
    const val REGISTER_SUCCESS = "REGISTER_SUCCESS"
    const val LOGIN_SUCCESS = "LOGIN_SUCCESS"
    const val OTP_VERIFICATION_FAILED = "OTP_VERIFICATION_FAILED"
    const val PAIRED_DEVICE_SETUP_STARTED = "PAIRED_DEVICE_SETUP_STARTED"
    const val PAIRED_DEVICE_SETUP_SUCCESS = "PAIRED_DEVICE_SETUP_SUCCESS"
    const val PAIRED_DEVICE_SETUP_FAILED = "PAIRED_DEVICE_SETUP_FAILED"
    const val PAIR_DEVICE_UNABLETOPAIR = "PAIR_DEVICE_UNABLETOPAIR"
    const val FOOTER_SUMMARY_CLICK = "FOOTER_SUMMARY_CLICK"
    const val FOOTER_CHALLENGES_CLICK = "FOOTER_CHALLENGES_CLICK"
    const val FOOTER_SHOP_CLICK = "FOOTER_SHOP_CLICK"
    const val SEARCH_BAR_CLICKED = "SEARCH_BAR_CLICKED"
    const val SEARCH_BAR_RESULTED = "SEARCH_BAR_RESULTED"
    const val FOOTER_MYDEVICES_CLICK = "FOOTER_MYDEVICES_CLICK"
    const val ACCOUNT_SET_UP_STARTED = "ACCOUNT_SET_UP_STARTED"
    const val ACCOUNT_SET_UP_SUCCESS = "ACCOUNT_SET_UP_SUCCESS"
    const val STEP_COUNT_PAGE_VIEWED = "STEP_COUNT_PAGE_VIEWED"
    const val DISTANCE_PAGE_VIEWED = "DISTANCE_PAGE_VIEWED"
    const val HEART_RATE_PAGE_VIEWED = "HEART_RATE_PAGE_VIEWED"
    const val SLEEP_PAGE_VIEWED = "SLEEP_PAGE_VIEWED"
    const val BLOOD_OXYGEN_PAGE_VIEWED = "BLOOD_OXYGEN_PAGE_VIEWED"
    const val STRESS_PAGE_VIEWED = "STRESS_PAGE_VIEWED"

    //home screen
    const val HAMBURGER_MENU_CLICK = "HAMBURGER_MENU_CLICK"
    const val HOMESCREEN_BANNER_CLICK = "HOMESCREEN_BANNER_CLICK"
    const val HOMESCREEN_BANNER_POS = "HOMESCREEN_BANNER_POS"
    const val HOMESCREEN_HEALTHOVERVIEW_VIEWALL_CLICK = "HOMESCREEN_HEALTHOVERVIEW_VIEWALL_CLICK"
    const val HOMESCREEN_HEALTHOVERVIEW_EDITHEALTHOVERVIEW_CLICK =
        "HOMESCREEN_HEALTHOVERVIEW_EDITHEALTHOVERVIEW_CLICK"
    const val HOMESCREEN_HEALTHOVERVIEW_STEPSCOUNT_CLICK =
        "HOMESCREEN_HEALTHOVERVIEW_STEPSCOUNT_CLICK"
    const val HOMESCREEN_HEALTHOVERVIEW_HEARTRATE_CLICK =
        "HOMESCREEN_HEALTHOVERVIEW_HEARTRATE_CLICK"
    const val HOMESCREEN_HEALTHOVERVIEW_SLEEP_CLICK = "HOMESCREEN_HEALTHOVERVIEW_SLEEP_CLICK"
    const val HOMESCREEN_HEALTHOVERVIEW_BLOODOXYGEN_CLICK =
        "HOMESCREEN_HEALTHOVERVIEW_BLOODOXYGEN_CLICK"
    const val HOMESCREEN_HEALTHOVERVIEW_STRESS_CLICK = "HOMESCREEN_HEALTHOVERVIEW_STRESS_CLICK"
    const val HOMESCREEN_HEALTHOVERVIEW_DISTANCE_CLICK = "HOMESCREEN_HEALTHOVERVIEW_DISTANCE_CLICK"
    const val HOMESCREEN_HEALTHOVERVIEW_BODYTEMPERATURE_CLICK =
        "HOMESCREEN_HEALTHOVERVIEW_BODYTEMPERATURE_CLICK"
    const val HOMESCREEN_RECENTWORKOUTS_VIEWALL_CLICK = "HOMESCREEN_RECENTWORKOUTS_VIEWALL_CLICK"

    //My Profile Page
    const val ACCOUNT_BADGES_CLICK = "ACCOUNT_BADGES_CLICK"
    const val ACCOUNT_BUDDIES_CLICK = "ACCOUNT_BUDDIES_CLICK"
    const val ACCOUNT_GOALS_CLICK = "ACCOUNT_GOALS_CLICK"
    const val GOALS_EDIT_CLICK = "GOALS_EDIT_CLICK"
    const val ACCOUNT_ORDERS_CLICK = "ACCOUNT_ORDERS_CLICK"
    const val ACCOUNT_HELP_CLICK = "ACCOUNT_HELP_CLICK"
    const val ACCOUNT_FEEDBACK_CLICK = "ACCOUNT_FEEDBACK_CLICK"
    const val ACCOUNT_ABOUT_CLICK = "ACCOUNT_ABOUT_CLICK"
    const val ACCOUNT_MYPROFILE_CLICK = "ACCOUNT_MYPROFILE_CLICK"
    const val ACCOUNT_MYPROFILE_EDIT_CLICK = "ACCOUNT_MYPROFILE_EDIT_CLICK"
    const val PROFILE_UPDATE = "PROFILE_UPDATE"

    //my device page
    const val MYDEVICE_DEVICEMANAGEMENT_CLICK = "MYDEVICE_DEVICEMANAGEMENT_CLICK"
    const val MYDEVICE_WATCHFACES_CLICK = "MYDEVICE_WATCHFACES_CLICK"
    const val MYDEVICE_NOTIFICATION_CLICK = "MYDEVICE_NOTIFICATION_CLICK"
    const val MYDEVICE_CALLALERT_CLICK = "MYDEVICE_CALLALERT_CLICK"
    const val MYDEVICE_HEALTHMONITOR_CLICK = "MYDEVICE_HEALTHMONITOR_CLICK"
    const val MYDEVICE_MYALARMS_CLICK = "MYDEVICE_MYALARMS_CLICK"
    const val MYDEVICE_GOOGLEFIT_CLICK = "MYDEVICE_GOOGLEFIT_CLICK"
    const val MYDEVICE_MYCONTACTS_CLICK = "MYDEVICE_MYCONTACTS_CLICK"
    const val MYDEVICE_QUICKREPLY_CLICK = "MYDEVICE_QUICKREPLY_CLICK"
    const val MYDEVICE_WEATHERSETTINGS_CLICK = "MYDEVICE_WEATHERSETTINGS_CLICK"
    const val MYDEVICE_STOCKS_CLICK = "MYDEVICE_STOCKS_CLICK"
    const val MYDEVICE_WORLDCLOCK_CLICK = "MYDEVICE_WORLDCLOCK_CLICK"
    const val MYDEVCIE_FINDMYDEVICE_CLICK = "MYDEVCIE_FINDMYDEVICE_CLICK"
    const val MYDEVICE_CAMERASHUTTER_CLICK = "MYDEVICE_CAMERASHUTTER_CLICK"
    const val MYDEVICE_DEVICESETTING_CLICK = "MYDEVICE_DEVICESETTING_CLICK"
    const val MYDEVICE_UNPAIRDEVICE_CLICK = "MYDEVICE_UNPAIRDEVICE_CLICK"
    const val PAIR_DEVICE_PAIR_LATER_CLICK = "PAIR_DEVICE_PAIR_LATER_CLICK"

    //
    const val MYDEVICE_CAMERA_SWITCH = "MYDEVICE_CAMERA_SWITCH"
    const val MYDEVICE_WRIST_SENSE = "MYDEVICE_WRIST_SENSE"
    const val MYDEVICE_UPLOAD_AGPS = "MYDEVICE_UPLOAD_AGPS"
    const val MYDEVICE_LANGUAGE_SETTINGS = "MYDEVICE_LANGUAGE_SETTINGS"

    //activity track
    const val ACTIVITY_SYNC = "ACTIVITY_SYNC"

    //profile setup
    const val PROFILE_DETAILS_SKIPPED_CLICK = "PROFILE_DETAILS_SKIPPED_CLICK"
    const val PROFILE_DETAILS_CONTINUE_CLICK = "PROFILE_DETAILS_CONTINUE_CLICK"

    //health overview
    const val HEALTH_OVERVIEW_STEP_COUNT_CLICK = "HEALTH_OVERVIEW_STEP_COUNT_CLICK"
    const val HEALTH_OVERVIEW_DISTANCE_CLICK = "HEALTH_OVERVIEW_DISTANCE_CLICK"
    const val HEALTH_OVERVIEW_HEART_RATE_CLICK = "HEALTH_OVERVIEW_HEART_RATE_CLICK"
    const val HEALTH_OVERVIEW_SLEEP_CLICK = "HEALTH_OVERVIEW_SLEEP_CLICK"
    const val HEALTH_OVERVIEW_BLOOD_OXYGEN_CLICK = "HEALTH_OVERVIEW_BLOOD_OXYGEN_CLICK"
    const val HEALTH_OVERVIEW_STRESS_CLICK = "HEALTH_OVERVIEW_STRESS_CLICK"
    const val HEALTH_OVERVIEW_BODY_TEMPREATURE_CLICK = "HEALTH_OVERVIEW_BODY_TEMPREATURE_CLICK"

    //workout page
    const val WORKOUT_LIST_PAGE_VISIT = "WORKOUT_LIST_PAGE_VISIT"

    //    const val WORKOUT_DETAILS_PAGE_VISIT = "WORKOUT_DETAILS_PAGE_VISIT"
    const val ACTIVITY_DETAIL_PAGE_VISIT = "ACTIVITY_DETAIL_PAGE_VISIT_"
    const val WORKOUT_SHARE_CLICK = "WORKOUT_SHARE_CLICK"
    const val WORKOUT_FEEDBACK_CLICK = "WORKOUT_FEEDBACK_CLICK"

    //share workout
    const val SHARE_WORKOUT_VIA_INSTAGRAM_CLICK = "SHARE_WORKOUT_VIA_INSTAGRAM_CLICK"
    const val SHARE_WORKOUT_VIA_WHATSAPP_CLICK = "SHARE_WORKOUT_VIA_WHATSAPP_CLICK"
    const val SHARE_WORKOUT_SAVE_INSIDE_DEVICE_CLICK = "SHARE_WORKOUT_SAVE_INSIDE_DEVICE_CLICK"
    const val SHARE_WORKOUT_VIA_OTHERS_TOOLS_CLICK = "SHARE_WORKOUT_VIA_OTHERS_TOOLS_CLICK"
    const val SHARE_WORKOUT_IMAGE_CHANGE_CLICK = "SHARE_WORKOUT_IMAGE_CHANGE_CLICK"

    //feedback
    const val FEEDBACK_HELP_CLICK = "FEEDBACK_HELP_CLICK"
    const val FEEDBACK_SUBMIT_CLICK = "FEEDBACK_SUBMIT_CLICK"

    //help
    const val HELP_BATTERY_OPTIMIZATION_PAGE_VISIT = "HELP_BATTERY_OPTIMIZATION_PAGE_VISIT"
    const val HELP_BACKGROUND_LOCK_PAGE_VISIT = "HELP_BACKGROUND_LOCK_PAGE_VISIT"
    const val HELP_LOCATION_PERMISSION_PAGE_VISIT = "HELP_LOCATION_PERMISSION_PAGE_VISIT"
    const val HELP_TROUBLESHOOTING_PAGE_VISIT = "HELP_TROUBLESHOOTING_PAGE_VISIT"
    const val HELP_FAQ_PAGE_VISIT = "HELP_FAQ_PAGE_VISIT"
    const val HELP_HEART_RATE_PAGE_VISIT = "HELP_HEART_RATE_PAGE_VISIT"
    const val HELP_SLEEP_PAGE_VISIT = "HELP_SLEEP_PAGE_VISIT"
    const val HELP_BLOOD_OXYGEN_PAGE_VISIT = "HELP_BLOOD_OXYGEN_PAGE_VISIT"
    const val HELP_STRESS_PAGE_VISIT = "HELP_STRESS_PAGE_VISIT"
    const val HELP_STEPS_PAGE_VISIT = "HELP_STEPS_PAGE_VISIT"
    const val HELP_DISTANCE_PAGE_VISIT = "HELP_DISTANCE_PAGE_VISIT"
    const val HELP_BODY_TEMPREATURE_PAGE_VISIT = "HELP_BODY_TEMPREATURE_PAGE_VISIT"

    //my device management
    const val MY_DEVICE_CHECK_FOR_UPDATES_CLICK = "MY_DEVICE_CHECK_FOR_UPDATES_CLICK"
    const val MY_DEVICE_WARRANTY_REGISTRATION_CLICK = "MY_DEVICE_WARRANTY_REGISTRATION_CLICK"
    const val MY_DEVICE_UNPAIR_CLICK = "MY_DEVICE_UNPAIR_CLICK"
    const val MY_DEVICE_WATCH_UPDATE_INSTALL_CLICK = "MY_DEVICE_WATCH_UPDATE_INSTALL_CLICK"

    //watch faces
    const val WATCH_FACES_CUSTOM_CREATE_NOW_CLICK = "WATCH_FACES_CUSTOM_CREATE_NOW_CLICK"
    const val WATCH_FACES_VIEW_MORE_CLICK = "WATCH_FACES_VIEW_MORE_CLICK"
    const val WATCH_FACES_DETAILS_PAGE_VISIT = "WATCH_FACES_DETAILS_PAGE_VISIT"
    const val WATCH_FACES_UPDATED_CLICK = "WATCH_FACES_UPDATED_CLICK"

    //notification
    const val APP_NOTIFICATION_CLICK = "APP_NOTIFICATION_CLICK"
    const val APP_NOTIFICATION_SEARCH_CLICK = "APP_NOTIFICATION_SEARCH_CLICK"
    const val APP_NOTIFICATION_SAVE_CHANGES_CLICK = "APP_NOTIFICATION_SAVE_CHANGES_CLICK"
    const val SMS_ALERT_CLICK = "SMS_ALERT_CLICK"
    const val MY_REMINDER_PAGE_VISIT = "MY_REMINDER_PAGE_VISIT"
    const val MY_REMINDER_ADD_REMINDER_CLICK = "MY_REMINDER_ADD_REMINDER_CLICK"
    const val MY_REMINDER_ADD_REMINDER_SAVE_CLICK = "MY_REMINDER_ADD_REMINDER_SAVE_CLICK"
    const val MY_REMINDER_EDIT_CLICK = "MY_REMINDER_EDIT_CLICK"

    //call alert
    const val CALL_ALERT_CLICK = "CALL_ALERT_CLICK"
    const val BLUETOOTH_CALLING_CLICK = "BLUETOOTH_CALLING_CLICK"

    //health monitor
    const val HEART_RATE_PAGE_VISIT = "HEART_RATE_PAGE_VISIT"
    const val HEART_RATE_AUTO_HR_CLICK = "HEART_RATE_AUTO_HR_CLICK"
    const val RAPID_EYE_PAGE_VISIT = "RAPID_EYE_PAGE_VISIT"
    const val RAPID_EYE_MOVEMENT_CLICK = "RAPID_EYE_MOVEMENT_CLICK"
    const val DRINK_WATER_PAGE_VISIT = "DRINK_WATER_PAGE_VISIT"
    const val DRINK_WATER_CLICK = "DRINK_WATER_CLICK"
    const val DRINK_WATER_EDIT_CLICK = "DRINK_WATER_EDIT_CLICK"
    const val HAND_WASH_PAGE_VISIT = "HAND_WASH_PAGE_VISIT"
    const val HAND_WASH_CLICK = "HAND_WASH_CLICK"
    const val HAND_WASH_EDIT_CLICK = "HAND_WASH_EDIT_CLICK"
    const val IDLE_ALERT_PAGE_VISIT = "IDLE_ALERT_PAGE_VISIT"
    const val IDLE_ALERT_CLICK = "IDLE_ALERT_CLICK"
    const val IDLE_ALERT_EDIT_CLICK = "IDLE_ALERT_EDIT_CLICK"
    const val SPO2_PAGE_VISIT = "SPO2_PAGE_VISIT"
    const val FEMALE_TRACKER_PAGE_VISIT = "FEMALE_TRACKER_PAGE_VISIT"
    const val MEDICINE_REMINDER_PAGE_VISIT = "MEDICINE_REMINDER_PAGE_VISIT"
    const val MEAL_REMINDER_PAGE_VISIT = "MEAL_REMINDER_PAGE_VISIT"
    const val WALK_REMINDER_PAGE_VISIT = "WALK_REMINDER_PAGE_VISIT"

    //my alarms
    const val MY_ALARMS_ADD_REMINDER_CLICK = "MY_ALARMS_ADD_REMINDER_CLICK"
    const val MY_ALARMS_ADD_ALARMS_SAVE_CLICK = "MY_ALARMS_ADD_ALARMS_SAVE_CLICK"
    const val MY_ALARMS_EDIT_CLICK = "MY_ALARMS_EDIT_CLICK"
    const val MY_ALARM_ENABLED_CLICK = "MY_ALARM_ENABLED_CLICK"

    //google fit
    const val GOOGLE_FIT_CLICK = "GOOGLE_FIT_CLICK"

    //Help and Support
    const val HELP_AND_SUPPORT = "HELP_AND_SUPPORT"
    const val SUPPORT = "SUPPORT"

    //my contact
    const val MY_CONTACT_ADD_CLICK = "MY_CONTACT_ADD_CLICK"
    const val MY_CONTACT_ADD_CONTACT_SAVE_CLICK = "MY_CONTACT_ADD_CONTACT_SAVE_CLICK"
    const val MY_CONTACT_EDIT_CLICK = "MY_CONTACT_EDIT_CLICK"

    //quick reply
    const val QUICK_REPLY_ADD_CLICK = "QUICK_REPLY_ADD_CLICK"
    const val QUICK_REPLY_EDIT_CLICK = "QUICK_REPLY_EDIT_CLICK"
    const val QUICK_REPLY_DELETE_CLICK = "QUICK_REPLY_DELETE_CLICK"

    //weather setting
    const val WEATHER_SETTING_CLICK = "WEATHER_SETTING_CLICK"
    const val WEATHER_SETTING_LOCATION_PERMISSION_CLICK =
        "WEATHER_SETTING_LOCATION_PERMISSION_CLICK"

    //stock
    const val STOCKS_ADD_CLICK = "STOCKS_ADD_CLICK"
    const val STOCKS_EDIT_CLICK = "STOCKS_EDIT_CLICK"
    const val STOCKS_SEARCH_CLICK = "STOCKS_SEARCH_CLICK"
    const val STOCKS_DELETE_CLICK = "STOCKS_DELETE_CLICK"

    //world clock
    const val CLOCK_ADD_CLICK = "CLOCK_ADD_CLICK"
    const val CLOCK_EDIT_CLICK = "CLOCK_EDIT_CLICK"
    const val CLOCK_SEARCH_CLICK = "CLOCK_SEARCH_CLICK"
    const val CLOCK_DELETE_CLICK = "CLOCK_DELETE_CLICK"

    const val FIND_DEVICE_SEARCH_CLICK = "FIND_DEVICE_SEARCH_CLICK"

    //explore page
    const val EXPLORE_VIEW_ALL_CLICK = "EXPLORE_VIEW_ALL_CLICK"
    const val EXPLORE_DETAILS_PAGE_VISIT = "EXPLORE_DETAILS_PAGE_VISIT"
    const val EXPLORE_JOIN_CHALLANGE_CLICK = "EXPLORE_JOIN_CHALLANGE_CLICK"
    const val EXPLORE_LEAVE_CHALLANGE_CLICK = "EXPLORE_LEAVE_CHALLANGE_CLICK"
    const val EXPLORE_ABOUT_CHALLANGE_CLICK = "EXPLORE_ABOUT_CHALLANGE_CLICK"

    //challange event
    const val CHALLENGES_NEW_CLICK = "CHALLENGES_NEW_CLICK"
    const val CHALLENGES_JOINED_CLICK = "CHALLENGES_JOINED_CLICK"
    const val CHALLENGES_COMPLETED_CLICK = "CHALLENGES_COMPLETED_CLICK"
    const val CHALLENGE_NEW_ITEM_CLICK = "CHALLENGE_NEW_ITEM_CLICK"
    const val CHALLENGE_JOINED_ITEM_CLICK = "CHALLENGE_JOINED_ITEM_CLICK"
    const val CHALLENGE_COMPLETED_ITEM_CLICK = "CHALLENGE_COMPLETED_ITEM_CLICK"
    const val CHALLENGEDETAILSPAGE_JOINCHALLENGE_CLICK = "CHALLENGEDETAILSPAGE_JOINCHALLENGE_CLICK"
    const val CHALLENGEDETAILSPAGE_INVITECHALLENGE_CLICK =
        "CHALLENGEDETAILSPAGE_INVITECHALLENGE_CLICK"
    const val CHALLENGEDETAILSPAGE_SHARECHALLENGE_CLICK =
        "CHALLENGEDETAILSPAGE_SHARECHALLENGE_CLICK"
    const val CHALLENGEDETAILSPAGE_LEADERBOARD_VIEWALL_CLICK =
        "CHALLENGEDETAILSPAGE_LEADERBOARD_VIEWALL_CLICK"
    const val CHALLENGEDETAILSPAGE_LEAVECHALLENGE_CLICK =
        "CHALLENGEDETAILSPAGE_LEAVECHALLENGE_CLICK"

    //updated event name
    const val LEADERBOARD_VIEWALL_CLICK = "LEADERBOARD_VIEWALL_CLICK"
    const val LEADERBOARD_BUDDIES_CLICK = "LEADERBOARD_BUDDIES_CLICK"
    const val HEALTH_OVERVIEW_CALORIES_CLICK = "HEALTH_OVERVIEW_CALORIES_CLICK"
    const val HOMESCREEN_HEALTHOVERVIEW_CALORIES_CLICK = "HOMESCREEN_HEALTHOVERVIEW_CALORIES_CLICK"
    const val CALORIES_DAY_CLICK = "CALORIES_DAY_CLICK"
    const val CALORIES_WEEK_CLICK = "CALORIES_WEEK_CLICK"
    const val CALORIES_MONTH_CLICK = "CALORIES_MONTH_CLICK"
    const val CALORIES_YEAR_CLICK = "CALORIES_YEAR_CLICK"

    const val STEPS_DAY_CLICK = "STEPS_DAY_CLICK"
    const val STEPS_WEEK_CLICK = "STEPS_WEEK_CLICK"
    const val STEPS_MONTH_CLICK = "STEPS_MONTH_CLICK"
    const val STEPS_YEAR_CLICK = "STEPS_YEAR_CLICK"

    const val DISTANCE_DAY_CLICK = "DISTANCE_DAY_CLICK"
    const val DISTANCE_WEEK_CLICK = "DISTANCE_WEEK_CLICK"
    const val DISTANCE_MONTH_CLICK = "DISTANCE_MONTH_CLICK"
    const val DISTANCE_YEAR_CLICK = "DISTANCE_YEAR_CLICK"
    const val HEART_RATE_DAY_CLICK = "HEART_RATE_DAY_CLICK"
    const val HEART_RATE_WEEK_CLICK = "HEART_RATE_WEEK_CLICK"
    const val HEART_RATE_MONTH_CLICK = "HEART_RATE_MONTH_CLICK"
    const val HEART_RATE_YEAR_CLICK = "HEART_RATE_YEAR_CLICK"
    const val BLOOD_OXYGEN_DAY_CLICK = "BLOOD_OXYGEN_DAY_CLICK"
    const val BLOOD_OXYGEN_WEEK_CLICK = "BLOOD_OXYGEN_WEEK_CLICK"
    const val BLOOD_OXYGEN_MONTH_CLICK = "BLOOD_OXYGEN_MONTH_CLICK"
    const val BLOOD_OXYGEN_YEAR_CLICK = "BLOOD_OXYGEN_YEAR_CLICK"
    const val SLEEP_DAY_CLICK = "SLEEP_DAY_CLICK"
    const val SLEEP_WEEK_CLICK = "SLEEP_WEEK_CLICK"
    const val SLEEP_MONTH_CLICK = "SLEEP_MONTH_CLICK"
    const val SLEEP_YEAR_CLICK = "SLEEP_YEAR_CLICK"
    const val STRESS_DAY_CLICK = "STRESS_DAY_CLICK"
    const val STRESS_WEEK_CLICK = "STRESS_WEEK_CLICK"
    const val STRESS_MONTH_CLICK = "STRESS_MONTH_CLICK"
    const val STRESS_YEAR_CLICK = "STRESS_YEAR_CLICK"

    const val BODYTEMPERATURE_DAY_CLICK = "BODYTEMPERATURE_DAY_CLICK"
    const val BODYTEMPERATURE_WEEK_CLICK = "BODYTEMPERATURE_WEEK_CLICK"
    const val BODYTEMPERATURE_MONTH_CLICK = "BODYTEMPERATURE_MONTH_CLICK"
    const val BODYTEMPERATURE_YEAR_CLICK = "BODYTEMPERATURE_YEAR_CLICK"

    const val HOMEPAGE_WATCHFACE_BANNER_CLICK = "HOMEPAGE_WATCHFACE_BANNER_CLICK"
    const val WATCHFACE_NEWLY_ADDED_ITEM_CLICK = "WATCHFACE_NEWLY_ADDED_ITEM_CLICK"
    const val WATCHFACE_TOPDOWNLOAD_ITEM_CLICK = "WATCHFACE_TOPDOWNLOAD_ITEM_CLICK"
    const val WATCHFACE_DESIGNWISE_ITEM_CLICK = "WATCHFACE_DESIGNWISE_ITEM_CLICK"
    const val WATCHFACE_NEWLY_ADDED_VIEW_ALL_CLICK = "WATCHFACE_NEWLY_ADDED_VIEW_ALL_CLICK"
    const val WATCHFACE_TOPDOWNLOADED_VIEW_ALL_CLICK = "WATCHFACE_TOPDOWNLOADED_VIEW_ALL_CLICK"
    const val WATCHFACE_DESIGNWISE_VIEW_ALL_CLICK = "WATCHFACE_DESIGNWISE_VIEW_ALL_CLICK"
    const val WATCHFACE_RECENTLY_USED_ITEM_CLICK = "WATCHFACE_RECENTLY_USED_ITEM_CLICK"
    const val WATCHFACE_RECENTLY_USED_VIEW_ALL_CLICK = "WATCHFACE_RECENTLY_USED_VIEW_ALL_CLICK"
    const val WATCHFACE_ALL_CLICK = "WATCHFACE_ALL_CLICK"
    const val WATCHFACE_MYFAV_CLICK = "WATCHFACE_MYFAV_CLICK"
    const val MYBUDDIES_REQUEST_SENT_CLICK = "MYBUDDIES_REQUEST_SENT_CLICK"
    const val MYBUDDIES_REQUEST_RECEIVED_CLICK = "MYBUDDIES_REQUEST_RECEIVED_CLICK"


    const val CHALLENGES_USER_ASYNC_CLICK = "CHALLENGES_USER_ASYNC_CLICK"
    const val MY_BUDDIES_ADD_CONTACT_CLICK = "MY_BUDDIES_ADD_CONTACT_CLICK"
    const val MY_BUDDIES_NUDGE = "MY_BUDDIES_NUDGE"
    const val HELP_SUPPORT_CLICK = "HELP_SUPPORT_CLICK"

    //commented because remove after discussion with Akhil and Aayush(8th Dec 2022)
//    const val HELP_SUPPORT_NOTIFCATION_CLICK="HELP_SUPPORT_NOTIFCATION_CLICK"
//    const val HELP_SUPPORT_WATCHFACETRANSFER_CLICK="HELP_SUPPORT_WATCHFACETRANSFER_CLICK"
//    const val HELP_SUPPORT_BATT_CHARGE_CLICK="HELP_SUPPORT_BATT_CHARGE_CLICK"
//    const val HELP_SUPPORT_DATASYNC_CLICK="HELP_SUPPORT_DATASYNC_CLICK"
//    const val HELP_SUPPORT_BTCALLING_CLICK="HELP_SUPPORT_BTCALLING_CLICK"
//    const val HELP_SUPPORT_HARDWARERELATED_CLICK="HELP_SUPPORT_HARDWARERELATED_CLICK"
//    const val HELP_SUPPORT_CHALLENGES_REWARDS_CLICK="HELP_SUPPORT_CHALLENGES_REWARDS_CLICK"
//    const val HELP_SUPPORT_WATCH_APPUPDATE_CLICK="HELP_SUPPORT_WATCH_APPUPDATE_CLICK"
//    const val HELP_SUPPORT_ORDER_REFUNDQUERIES_CLICK="HELP_SUPPORT_ORDER_REFUNDQUERIES_CLICK"
//    const val HELP_SUPPORT_RAISEACOMPLAINT_CLICK="HELP_SUPPORT_RAISEACOMPLAINT_CLICK"
//    const val HELP_SUPPORT_PAIRING_CONNECTIVITY_CLICK="HELP_SUPPORT_PAIRING_CONNECTIVITY_CLICK"
    const val HOMEPAGE_ALERT_COMPLETEWATCHSETUP_CLICK = "HOMEPAGE_ALERT_COMPLETEWATCHSETUP_CLICK"
    const val HOMEPAGE_ALERT_PAIRING_CONNECTIVITY_CLICK =
        "HOMEPAGE_ALERT_PAIRING_CONNECTIVITY_CLICK"
    const val HOMEPAGE_ALERT_WATCH_NOTIFICATION_CLICK = "HOMEPAGE_ALERT_WATCH_NOTIFICATION_CLICK"
    const val HOMEPAGE_ALERT_HELP_SUPPORT_CLICK = "HOMEPAGE_ALERT_HELP_SUPPORT_CLICK"
    const val FEEDBACK_CLICK = "FEEDBACK_CLICK"
    const val USERPROFILE_FITNESS_HEALTH_CLICK = "USERPROFILE_FITNESS_HEALTH_CLICK"

    //friends module event
    const val FOOTER_FRIENDS_CLICK = "FOOTER_FRIENDS_CLICK"
    const val FRIENDS_ACTIVITYTAB_CLICK = "FRIENDS_ACTIVITYTAB_CLICK"
    const val FRIENDS_COMPETITIONTAB_CLICK = "FRIENDS_COMPETITIONTAB_CLICK"
    const val ADDFRIENDS_CLICK = "ADDFRIENDS_CLICK"
    const val ACTIVITY_ADDFRIENDS_CLICK = "ACTIVITY_ADDFRIENDS_CLICK"
    const val COMPETITION_ADDFRIENDS_CLICK = "COMPETITION_ADDFRIENDS_CLICK"
    const val CONTACTS_ADD_CLICK = "CONTACTS_ADD_CLICK"
    const val CONTACTS_REMOVE_CLICK = "CONTACTS_REMOVE_CLICK"
    const val COMMONINTEREST_ADD_CLICK = "COMMONINTEREST_ADD_CLICK"
    const val COMMONINTEREST_REMOVE_CLICK = "COMMONINTEREST_REMOVE_CLICK"
    const val PASTWINNERS_ADD_CLICK = "PASTWINNERS_ADD_CLICK"
    const val PASTWINNERS_REMOVE_CLICK = "PASTWINNERS_REMOVE_CLICK"
    const val NEARME_ADD_CLICK = "NEARME_ADD_CLICK"
    const val NEARME_REMOVE_CLICK = "NEARME_REMOVE_CLICK"
    const val NEAR_ME_EDIT_YOUR_LOCATION_CLICK = "NEAR_ME_EDIT_YOUR_LOCATION_CLICK"
    const val NEAR_ME_EDIT_YOUR_LOCATION_SAVE_CLICK = "NEAR_ME_EDIT_YOUR_LOCATION_SAVE_CLICK"
    const val FRIENDS_REQUESTSENT_RECEIVED_CLICK = "FRIENDS_REQUESTSENT_RECEIVED_CLICK"
    const val ACTIVITY_DURATIONFILTER_CLICK = "ACTIVITY_DURATIONFILTER_CLICK"
    const val EMOJI_CLICK = "EMOJI_CLICK"
    const val ACTIVITYSUMMARY_EMOJI_CLICK = "ACTIVITYSUMMARY_EMOJI_CLICK"
    const val FRIENDSPROFILE_EMOJI_CLICK = "FRIENDSPROFILE_EMOJI_CLICK"
    const val ACTIVITY_FRIENDSPROFILE_CLICK = "ACTIVITY_FRIENDSPROFILE_CLICK"
    const val REQUESTRECEIVED_CLICK = "REQUESTRECEIVED_CLICK"
    const val REQUESTSENT_CLICK = "REQUESTSENT_CLICK"
    const val RR_COMPETITION_ACCEPT_CLICK = "RR_COMPETITION_ACCEPT_CLICK"
    const val RR_COMPETITION_DECLINE_CLICK = "RR_COMPETITION_DECLINE_CLICK"
    const val RR_FRIENDREQUEST_ACCEPT_CLICK = "RR_FRIENDREQUEST_ACCEPT_CLICK"
    const val RR_FRIENDREQUEST_DECLINE_CLICK = "RR_FRIENDREQUEST_DECLINE_CLICK"
    const val COMPETE_COMPETEFRIENDS_CLICK = "COMPETE_COMPETEFRIENDS_CLICK"
    const val COMPETE_REQUESTSENT_CLICK = "COMPETE_REQUESTSENT_CLICK"
    const val FRIENDPROFILE_ADDFRIENDS_CLICK = "FRIENDPROFILE_ADDFRIENDS_CLICK"
    const val FRIENDPROFILE_ACCEPTFRIENDS_CLICK = "FRIENDPROFILE_ACCEPTFRIENDS_CLICK"
    const val FRIENDPROFILE_DECLINEFRIENDS_CLICK = "FRIENDPROFILE_DECLINEFRIENDS_CLICK"
    const val FRIENDPROFILE_REMOVEFRIENDS_CLICK = "FRIENDPROFILE_REMOVEFRIENDS_CLICK"
    const val FRIENDPROFILE_ACTIVITY_CLICK = "FRIENDPROFILE_ACTIVITY_CLICK"
    const val FRIENDPROFILE_CHALLENGES_CLICK = "FRIENDPROFILE_CHALLENGES_CLICK"
    const val FRIENDPROFILE_BADGES_CLICK = "FRIENDPROFILE_BADGES_CLICK"
    const val FRIENDPROFILE_COMPETENOW_CLICK = "FRIENDPROFILE_COMPETENOW_CLICK"
    const val FRIENDPROFILE_CHALLENGES_JOINCHALLENGE_CLICK =
        "FRIENDPROFILE_CHALLENGES_JOINCHALLENGE_CLICK"
    const val FRIENDPROFILE_LOCATIONEDIT_CLICK = "FRIENDPROFILE_LOCATIONEDIT_CLICK"
    const val FRIENDPROFILE_INTERESTEDIT_CLICK = "FRIENDPROFILE_INTERESTEDIT_CLICK"


    //on-boarding event
    const val WELCOME_PAGE_CONTINUE_BUTTON_CLICK = "WELCOME_PAGE_CONTINUE_BUTTON_CLICK"
    const val LAND_ON_START_FITNESS_PAGE_VISIT = "LAND_ON_START_FITNESS_PAGE_VISIT"
    const val LAND_ON_ENTER_PHONE_NO_PAGE_VISIT = "LAND_ON_ENTER_PHONE_NO_PAGE_VISIT"
    const val CONTINUE_ENTER_PHONE_NUMBER_CLICK = "CONTINUE_ENTER_PHONE_NUMBER_CLICK"
    const val LAND_ON_ENTER_OTP_PAGE_VISIT = "LAND_ON_ENTER_OTP_PAGE_VISIT"
    const val CONTINUE_OTP_CLICK = "CONTINUE_OTP_CLICK"
    const val REGISTRATION_OTP_VERIFIED_SUCCESSFULLY = "REGISTRATION_OTP_VERIFIED_SUCCESSFULLY"
    const val LAND_ON_LOOK_FOR_DEVICE_PAGE_VISIT = "LAND_ON_LOOK_FOR_DEVICE_PAGE_VISIT"
    const val CONTINUE_ENTER_NAME_CLICK = "CONTINUE_ENTER_NAME_CLICK"
    const val LAND_ON_ENTER_AGE_PAGE_VISIT = "LAND_ON_ENTER_AGE_PAGE_VISIT"
    const val CONTINUE_ENTER_AGE_CLICK = "CONTINUE_ENTER_AGE_CLICK"
    const val LAND_ON_ENTER_GENDER_PAGE_VISIT = "LAND_ON_ENTER_GENDER_PAGE_VISIT"
    const val CONTINUE_ENTER_GENDER_CLICK = "CONTINUE_ENTER_GENDER_CLICK"
    const val LAND_ON_ENTER_WEIGHT_PAGE_VISIT = "LAND_ON_ENTER_WEIGHT_PAGE_VISIT"
    const val CONTINUE_ENTER_WEIGHT_CLICK = "CONTINUE_ENTER_WEIGHT_CLICK"
    const val LAND_ON_ENTER_HEIGHT_PAGE_VISIT = "LAND_ON_ENTER_HEIGHT_PAGE_VISIT"
    const val CONTINUE_ENTER_HEIGHT_CLICK = "CONTINUE_ENTER_HEIGHT_CLICK"
    const val LAND_ON_DAILY_GOAL_SET_PAGE_VISIT = "LAND_ON_DAILY_GOAL_SET_PAGE_VISIT"
    const val CONTINUE_ENTER_DAILY_GOAL_CLICK = "CONTINUE_ENTER_DAILY_GOAL_CLICK"
    const val LAND_ON_SET_UP_PROFILE_PAGE_VISIT = "LAND_ON_SET_UP_PROFILE_PAGE_VISIT"

    //reward page event (15/02/2023)
    const val HOMESCREEN_NORMAL_STEP_STREAK_CLICK = "HOMESCREEN_NORMAL_STEP_STREAK_CLICK"
    const val HOMESCREEN_REWARD_AWAITS_YOU_CLICK = "HOMESCREEN_REWARD_AWAITS_YOU_CLICK"
    const val HOMESCREEN_COIN_ICON_CLICK = "HOMESCREEN_COIN_ICON_CLICK"
    const val HOMESCREEN_ALERT_STEP_STREAK_CLICK = "HOMESCREEN_ALERT_STEP_STREAK_CLICK"

    const val REWARD_LANDING_PAGE_VISIT = "REWARD_LANDING_PAGE_VISIT"
    const val REWARD_ALL_TASKS_CLICK = "REWARD_ALL_TASKS_CLICK"
    const val REWARD_TASK_ITEM_CLICK = "REWARD_TASK_ITEM_CLICK"
    const val REWARD_COLLECT_COIN_CLICK = "REWARD_COLLECT_COIN_CLICK"
    const val REWARD_ALL_DEALS_CLICK = "REWARD_ALL_DEALS_CLICK"
    const val REWARD_ITEM_DEAL_CLICK = "REWARD_ITEM_DEAL_CLICK"
    const val REWARD_TRANSACTION_HISTORY_CLICK = "REWARD_TRANSACTION_HISTORY_CLICK"
    const val REWARDS_ABOUT_COIN_CLICK = "REWARDS_ABOUT_COIN_CLICK"
    const val REWARD_VOUCHER_PURCHASED_ICON_CLICK = "REWARD_VOUCHER_PURCHASED_ICON_CLICK"

    const val ALL_TASK_LANDING_PAGE_VISIT = "ALL_TASK_LANDING_PAGE_VISIT"
    const val ALL_TASKS_ITEM_CLICK = "ALL_TASKS_ITEM_CLICK"
    const val ALL_TASKS_COLLECT_COIN_CLICK = "ALL_TASKS_COLLECT_COIN_CLICK"
    const val ALL_DEAL_LANDING_PAGE_VISIT = "ALL_DEAL_LANDING_PAGE_VISIT"
    const val ALL_DEAL_ITEM_CLICK = "ALL_DEAL_ITEM_CLICK"


    const val VOUCHER_DETAIL_LANDING_PAGE_VISIT = "VOUCHER_DETAIL_LANDING_PAGE_VISIT"
    const val VOUCHER_DETAIL_PAGE_AVAIL_CLICK = "VOUCHER_DETAIL_PAGE_AVAIL_CLICK"
    const val VOUCHER_DETAIL_PAGE_REDEEM_CLICK = "VOUCHER_DETAIL_PAGE_REDEEM_CLICK"

    const val REWARD_TRANSACTION_HISTORY_LANDING_PAGE_VISIT =
        "REWARD_TRANSACTION_HISTORY_LANDING_PAGE_VISIT"
    const val MY_VOUCHER_PAGE_ACTIVE_VOUCHER_PAGE_VISIT =
        "MY_VOUCHER_PAGE_ACTIVE_VOUCHER_PAGE_VISIT"
    const val MY_VOUCHER_PAGE_EXPIRED_VOUCHER_PAGE_VISIT =
        "MY_VOUCHER_PAGE_EXPIRED_VOUCHER_PAGE_VISIT"
    const val MY_VOUCHER_PAGE_REDEEM_CLICK =
        "MY_VOUCHER_PAGE_REDEEM_CLICK"
    const val MY_VOUCHER_PAGE_NO_PURCHASE =
        "MY_VOUCHER_PAGE_NO_PURCHASE"

    const val REWARD_STEPS_GOAL = "REWARD_STEP_GOAL"
    const val REWARD_STEPS_REMAINING = "REWARD_STEP_REMAINING"
    const val REWARD_STEPS_CURRENT = "REWARD_STEPS_CURRENT"

    const val ACCOUNT_MY_PROFILE_LOGOUT_CLICK = "ACCOUNT_MY_PROFILE_LOGOUT_CLICK"
    const val ACCOUNT_MY_PROFILE_DELETE_ACCOUNT_CLICK = "ACCOUNT_MY_PROFILE_DELETE_ACCOUNT_CLICK"
    const val MY_DEVICE_WATHFACE_ITEM_CLICK = "MY_DEVICE_WATHFACE_ITEM_CLICK"
    const val CUSTOM_WATCHFACE_UPDATE_CLICK = "CUSTOM_WATCHFACE_UPDATE_CLICK"
    const val CHALLENGE_NEW_LIST_PAGE_VISIT = "CHALLENGE_NEW_LIST_PAGE_VISIT"
    const val CHALLENGE_JOIN_LIST_PAGE_VISIT = "CHALLENGE_JOIN_LIST_PAGE_VISIT"
    const val CHALLENGE_COMPLETED_LIST_PAGE_VISIT = "CHALLENGE_COMPLETED_LIST_PAGE_VISIT"
    const val STEP_STREAK_NORMAL_PAGE_VISIT = "STEP_STREAK_NORMAL_PAGE_VISIT"
    const val STEP_STREAK_ALERT_PAGE_VISIT = "STEP_STREAK_ALERT_PAGE_VISIT"

    //feeds
    const val FOOTER_COMMUNITY_CLICK = "FOOTER_COMMUNITY_CLICK"
    const val COMMUNITY_FEEDS_CLICK = "COMMUNITY_FEEDS_CLICK"
    const val COMMUNITY_FRIENDS_CLICK = "COMMUNITY_FRIENDS_CLICK"
    const val COMMUNITY_COMPETE_CLICK = "COMMUNITY_COMPETE_CLICK"
    const val COMMUNITY_NEWPOST_CLICK = "COMMUNITY_NEWPOST_CLICK"
    const val UPLOAD_CLICK = "UPLOAD_CLICK"
    const val ACTIVITYUPLOAD_CLICK = "ACTIVITYUPLOAD_CLICK"
    const val WORKOUTUPLOAD_CLICK = "WORKOUTUPLOAD_CLICK"
    const val CHALLENGESUPLOAD_CLICK = "CHALLENGESUPLOAD_CLICK"
    const val POSTUPLOAD_CLICK = "POSTUPLOAD_CLICK"
    const val EDITPOST_CLICK = "EDITPOST_CLICK"
    const val DELETEPOST_CLICK = "DELETEPOST_CLICK"
    const val REPORT_COMMENT_CLICK = "REPORT_COMMENT_CLICK"
    const val REPORTCOMMENT_ABUSIVE_CLICK = "REPORTCOMMENT_ABUSIVE_CLICK"
    const val REPORTCOMMENT_INAPPROPATE_CLICK = "REPORTCOMMENT_INAPPROPATE_CLICK"
    const val REPORTCOMMENT_SPAM_CLICK = "REPORTCOMMENT_SPAM_CLICK"
    const val REPORT_POST_CLICK = "REPORT_POST_CLICK"
    const val REPORTPOST_ABUSIVE_CLICK = "REPORTPOST_ABUSIVE_CLICK"
    const val REPORTPOST_INAPPROPATE_CLICK = "REPORTPOST_INAPPROPATE_CLICK"
    const val REPORTPOST_SPAM_CLICK = "REPORTPOST_SPAM_CLICK"
    const val FEED_EMOJI_CLICK = "FEED_EMOJI_CLICK"
    const val FEED_COMMENT_CLICK = "FEED_COMMENT_CLICK"
    const val NEWPOST_BACKGROUND_CLICK = "NEWPOST_BACKGROUND_CLICK"
    const val NEWPOST_LAYOUT_CLICK = "NEWPOST_LAYOUT_CLICK"
    const val LAYOUT_STYLE1_CLICK = "LAYOUT_STYLE1_CLICK"
    const val LAYOUT_STYLE2_CLICK = "LAYOUT_STYLE2_CLICK"
    const val COMMUNITY_MYPROFILE_CLICK = "COMMUNITY_MYPROFILE_CLICK"
    const val MYPROFILE_TIMELINE_CLICK = "MYPROFILE_TIMELINE_CLICK"
    const val MYFRIENDLIST_CLICK = "MYFRIENDLIST_CLICK"
    const val MYBADGESLIST_CLICK = "MYBADGESLIST_CLICK"
    const val MYPOSTLIST_CLICK = "MYPOSTLIST_CLICK"
    const val CHALLEGESBANNER_CLICK = "CHALLEGESBANNER_CLICK"
    const val FRIENDSBANNER_CLICK = "FRIENDSBANNER_CLICK"
    const val FEEDS_REPORTPOST_CLICK = "FEEDS_REPORTPOST_CLICK"
    const val FEEDS_REPORTPOST_ = "FEEDS_REPORTPOST_"//append dynamic value
    const val UT_REPORTPOST_ = "UT_REPORTPOST_"//append dynamic value
    const val UT_REPORTCOMMENT_ = "UT_REPORTPOST_"//append dynamic value

    const val UT_REPORTPOST_CLICK = "UT_REPORTPOST_CLICK"
    const val FEED_COMMENT_SUBMIT_CLICK = "FEED_COMMENT_SUBMIT_CLICK"
    const val FEEDS_REPORTCOMMENT_CLICK = "FEEDS_REPORTCOMMENT_CLICK"


    const val COMMUNITY_ADD_FRIENDS_CLICK = "COMMUNITY_ADD_FRIENDS_CLICK"
    const val COMMUNITY_COMPETITON_ADD_FRIENDS_CLICK = "COMMUNITY_COMPETITON_ADD_FRIENDS_CLICK"

    //NPL events
    const val NPL_HOMEPAGE_SCOREBOARD_CLICK = "NPL_HOMEPAGE_SCOREBOARD_CLICK"
    const val NPL_HOMEPAGE_NPL_CLICK = "NPL_HOMEPAGE_NPL_CLICK"
    const val NPL_TERMS_CONTINUE_CLICK = "NPL_TERMS_CONTINUE_CLICK"
    const val NPL_WALKTHROUGH_BACK_CLICK = "NPL_WALKTHROUGH_BACK_CLICK"
    const val NPL_WALKTHROUGH_NEXT_CLICK = "NPL_WALKTHROUGH_NEXT_CLICK"
    const val NPL_PAGE_VISIT = "NPL_PAGE_VISIT"
    const val NPL_HOME_INFO_ICON_CLICK = "NPL_HOME_INFO_ICON_CLICK"
    const val NPL_HOME_BACK_NAVIGATION_CLICK = "NPL_HOME_BACK_NAVIGATION_CLICK"
    const val NPL_TEAM_CHECKBOX_CLICK = "NPL_TEAM_CHECKBOX_CLICK"
    const val NPL_CONFIRM_TEAM_CLICK = "NPL_CONFIRM_TEAM_CLICK"
    const val NPL_HOME_BANNER_SCROLL = "NPL_HOME_BANNER_SCROLL"
    const val NPL_PREDICTION_HISTORY_CLICK = "NPL_PREDICTION_HISTORY_CLICK"
    const val NPL_PREDICTION_HISTORY_PAGE_VISIT = "NPL_PREDICTION_HISTORY_PAGE_VISIT"
    const val NPL_HOWTOPLAY_CLICK = "NPL_HOWTOPLAY_CLICK"
    const val NPL_HOWTOPLAY_PAGE_VISIT = "NPL_HOWTOPLAY_PAGE_VISIT"
    const val NPL_RAISE_COMPLAINT_CLICK = "NPL_RAISE_COMPLAINT_CLICK"
    const val NPL_HOME_TERMS_CLICK = "NPL_HOME_TERMS_CLICK"
    const val NPL_TERMS_PAGE_VISIT = "NPL_TERMS_PAGE_VISIT"
    const val NPL_CLAIM_WINS_ENTRY_CLICK = "NPL_CLAIM_WINS_ENTRY_CLICK"
    const val NPL_HOME_COLLECT_REWARD_CLICK = "NPL_HOME_COLLECT_REWARD_CLICK"
    const val NPL_CLAIMWINS_PAGE_VISIT = "NPL_CLAIMWINS_PAGE_VISIT"
    const val NPL_COLLECT_ALL_WINS_CLICK = "NPL_COLLECT_ALL_WINS_CLICK"
    const val NPL_CLAIMWINS_COLLECT_REWARD_CLICK = "NPL_CLAIMWINS_COLLECT_REWARD_CLICK"

    //NPL Quiz Event(19th April 2023)
    const val NPL_HOMEPAGE_QUIZ_CLICK = "NPL_HOMEPAGE_QUIZ_CLICK"
    const val NPL_START_QUIZ_CLICK = "NPL_START_QUIZ_CLICK"
    const val NPL_QUIZ_OPTION_SELECT = "NPL_QUIZ_OPTION_SELECT"
    const val NPL_QUIZ_END_DONE_CLICK = "NPL_QUIZ_END_DONE_CLICK"
    const val NPL_QUIZ_BACK_ICON_CLICK = "NPL_QUIZ_BACK_ICON_CLICK"
    const val NPL_QUIZ_CLOSER_QUIT_CLICK = "NPL_QUIZ_CLOSER_QUIT_CLICK"
    const val NPL_QUIZ_CLOSER_CANCEL_CLICK = "NPL_QUIZ_CLOSER_CANCEL_CLICK"


    const val LOW_BATTERY_NOTIFICATION = "LOW_BATTERY_NOTIFICATION"
    const val LOW_BATTERY_CHARGED = "LOW_BATTERY_CHARGED"
    const val LOW_BATTERY_NOTIFICATION_CLICKED = "LOW_BATTERY_NOTIFICATION_CLICKED"


    object PairingEvents {
        const val wn_pair_device_list = "wn_pair_device_list"

        const val wn_pair_later = "wn_pair_later"
        const val wn_pair_unable_to_connect_pairing =
            "wn_pair_unable_to_connect_pairing" // param (screen : find_device,pairing)
        const val wn_pair_unable_to_connect_fd =
            "wn_pair_unable_to_connect_fd"

        const val wn_pair_scan_clicked = "wn_pair_scan_clicked"

        const val wn_pair_scanning_start = "wn_pair_scanning_start"
        const val wn_pair_scanning_stop = "wn_pair_scanning_stop"// count : no of watches found

        const val wn_pair_device_clicked =
            "wn_pair_device_clicked" //name: bluetooth name, supported : true/false

        const val wn_pair_device_by_qr =
            "wn_pair_device_by_qr"  //name: bluetooth name, supported : true/false

        const val wn_pair_device_scan_by_qr = "wn_pair_device_scan_by_qr"

        const val wn_pair_device_back = "wn_pair_device_back"


        const val wn_pair_pairing_retry = "wn_pair_pairing_retry"
        const val wn_pair_pairing_start = "wn_pair_pairing_start"// name,mac, tryAgain

        const val wn_pair_pairing_failed =
            "wn_pair_pairing_failed"
        const val wn_pair_pairing_complete =
            "wn_pair_pairing_complete"// name,mac, time (seconds), status:complete/failed

        const val wn_pair_fetch_device_start = "wn_pair_fetch_device_start"
        const val wn_pair_fetch_device_ne = "wn_pair_fetch_device_ne"
        const val wn_pair_fetch_device_ge = "wn_pair_fetch_device_ge"
        const val wn_pair_fetch_device_complete =
            "wn_pair_fetch_device_complete"

        const val wn_pair_register_df_start = "wn_pair_register_df_start"
        const val wn_pair_register_df_ne = "wn_pair_register_df_ne"
        const val wn_pair_register_df_ge = "wn_pair_register_df_ge"
        const val wn_pair_register_df_complete =
            "wn_pair_register_df_complete"

        const val wn_pair_register_ud_start = "wn_pair_register_ud_start"
        const val wn_pair_register_ud_ne = "wn_pair_register_ud_ne"
        const val wn_pair_register_ud_ge = "wn_pair_register_ud_ge"
        const val wn_pair_register_ud_complete =
            "wn_pair_register_ud_complete"


        const val wn_pair_device_setup_start = "wn_pair_device_setup_start"
        const val wn_pair_device_setup_failed = "wn_pair_device_setup_failed"
        const val wn_pair_device_setup_complete =
            "wn_pair_device_setup_complete"//status: complete,failed
        const val wn_pair_try_again = "wn_pair_try_again" //state: specific to android
    }

    object WatchFaceEvents {


        const val wnc_face_apply = "wnc_face_apply"
        const val wnc_face_complete = "wnc_face_complete"
        const val wnc_face_failed = "wnc_face_failed"

        const val wnc_face_apply_failed_lb = "wnc_face_apply_failed_lb"
        const val wnc_face_apply_failed_ei = "wnc_face_apply_failed_ei"
        const val wnc_face_apply_failed_nc = "wnc_face_apply_failed_nc"


        const val wn_face_apply = "wn_face_apply"
        const val wn_face_apply_failed_lb = "wn_face_apply_failed_lb"
        const val wn_face_apply_failed_ei = "wn_face_apply_failed_ei"
        const val wn_face_apply_failed_nc = "wn_face_apply_failed_nc"

        const val wn_face_download_start = "wn_face_download_start"
        const val wn_face_download_complete = "wn_face_download_complete"
        const val wn_face_download_failed = "wn_face_download_failed"


        const val wn_face_start = "wn_face_start"
        const val wn_face_complete = "wn_face_complete"
        const val wn_face_failed = "wn_face_failed"


    }


    object ConnectionEvents {
        const val wn_connect_ask_reconnect =
            "wn_connect_ask_reconnect"//(param status: init/failed/connected,dName,dMac, supplier)
        const val wn_connect_ask_reconnect_connected = "wn_connect_ask_reconnect_connected"
        const val wn_connect_ask_reconnect_failed = "wn_connect_ask_reconnect_failed"

        const val wn_connect_reconnect_again = "wn_connect_reconnect_again" //(device)

        const val wn_connect_reconnect_disconnected = "wn_connect_reconnect_disconnected"
        const val wn_connect_reconnect_connected = "wn_connect_reconnect_connected" //(device)
        const val wn_connect_reconnect_failed = "wn_connect_reconnect_failed" //(device)

        const val wconnect_bt_status = "wconnect_bt_status"// (param device, on, off)
    }


    //watchface app events
    const val CUSTOMWF_CREATENOW = "CUSTOMWF_CREATENOW"
    const val CUSTOMWF_WALKTHROUGH_NEXT = "CUSTOMWF_WALKTHROUGH_NEXT"
    const val CUSTOMWF_WALKTHROUGH_PREVIOUS = "CUSTOMWF_WALKTHROUGH_PREVIOUS"
    const val CUSTOMWF_WALKTHROUGH_DONE = "CUSTOMWF_WALKTHROUGH_DONE"
    const val CUSTOMWF_WALKTHROUGH_SKIP = "CUSTOMWF_WALKTHROUGH_SKIP"
    const val CUSTOMWF_BACKGROUND_UPLOAD = "CUSTOMWF_BACKGROUND_UPLOAD"
    const val CUSTOMWF_FEATUREDIMAGE_ = "CUSTOMWF_FEATUREDIMAGE_"
    const val CUSTOMWF_FILTERS_ = "CUSTOMWF_FILTERS_"
    const val CUSTOMWF_FILTERS_INTENSITY = "CUSTOMWF_FILTERS_INTENSITY"
    const val CUSTOMWF_PLACEMENT_ = "CUSTOMWF_PLACEMENT_"
    const val CUSTOMWF_TEXTSTYLE_ = "CUSTOMWF_TEXTSTYLE_"
    const val CUSTOMWF_TEXTCOLOUR_ = "CUSTOMWF_TEXTCOLOUR_"
    const val CUSTOMWF_UPLOAD = "CUSTOMWF_UPLOAD"
    const val CUSTOMWF_TRANSFERRED = "CUSTOMWF_TRANSFERRED"
    const val CUSTOMWF_FAILED = "CUSTOMWF_FAILED"
    const val CUSTOMWF_BACKGROUND_GALLERY = "CUSTOMWF_BACKGROUND_GALLERY"
    const val CUSTOMWF_BACKGROUND_CAMERA = "CUSTOMWF_BACKGROUND_CAMERA"

    const val CUSTOMWF_TRANSFERRED_BACKGROUND="CUSTOMWF_TRANSFERRED_BACKGROUND_"
    const val CUSTOMWF_TRANSFERRED_IMAGE="CUSTOMWF_TRANSFERRED_IMAGE_"
    const val CUSTOMWF_TRANSFERRED_FEATURED="CUSTOMWF_TRANSFERRED_FEATURED_"
    const val CUSTOMWF_TRANSFERRED_FILTER="CUSTOMWF_TRANSFERRED_FILTER_"
    const val CUSTOMWF_TRANSFERRED_FILTERINTENSITY="CUSTOMWF_TRANSFERRED_FILTERINTENSITY_"
    const val CUSTOMWF_TRANSFERRED_PLACEMENT="CUSTOMWF_TRANSFERRED_PLACEMENT_"
    const val CUSTOMWF_TRANSFERRED_TEXTSTYLE="CUSTOMWF_TRANSFERRED_TEXTSTYLE_"
    const val CUSTOMWF_TRANSFERRED_TEXTCOLOUR="CUSTOMWF_TRANSFERRED_TEXTCOLOUR_"

    const val MYDEVICE_WATCHFACEITEM_CLICK="MYDEVICE_WATCHFACEITEM_CLICK"
    const val MYDEVICE_WATCHFACES_LEFTSCROLL="MYDEVICE_WATCHFACES_LEFTSCROLL"
    const val MYDEVICE_WATCHFACES_RIGHTSCROLL="MYDEVICE_WATCHFACES_RIGHTSCROLL"
    const val WATCHFACES_WALKTHROUGH_NEXT="WATCHFACES_WALKTHROUGH_NEXT"
    const val WATCHFACES_WALKTHROUGH_PREVIOUS="WATCHFACES_WALKTHROUGH_PREVIOUS"
    const val WATCHFACES_WALKTHROUGH_SKIP="WATCHFACES_WALKTHROUGH_SKIP"
    const val WATCHFACES_MYFAVOURITES="WATCHFACES_MYFAVOURITES"
    const val WATCHFACES_MYFAVOURITES_REMOVE="WATCHFACES_MYFAVOURITES_REMOVE"
    const val WATCHFACES_="WATCHFACES_"
    const val WATCHFACES_MY_CREATIONS_EDIT="WATCHFACES_MY_CREATIONS_EDIT"
    const val WATCHFACES_MY_CREATIONS_EDIT_REMOVE="WATCHFACES_MY_CREATIONS_EDIT_REMOVE"
    const val WATCHFACES_CATEGORY_CLICK="WATCHFACES_CATEGORY_CLICK"
    const val WATCHFACES_CATEGORY_ARROWCLICK="WATCHFACES_CATEGORY_ARROWCLICK"
    const val WATCHFACES_CATEGORY_LEFTSCROLL="WATCHFACES_CATEGORY_LEFTSCROLL"
    const val WATCHFACES_CATEGORY_SCROLLEND="WATCHFACES_CATEGORY_SCROLLEND"
    const val WATCHFACES_HAVINGISSUES="WATCHFACES_HAVINGISSUES"
    const val WATCHFACES_FAVOURITES_ADD="WATCHFACES_FAVOURITES_ADD"
    const val WATCHFACES_FAVOURITES_REMOVE="WATCHFACES_FAVOURITES_REMOVE"
    const val WATCHFACES_OPEN="WATCHFACES_OPEN"
    const val WATCHFACES_OPEN_CATEGORY="WATCHFACES_OPEN_CATEGORY"
    const val WATCHFACES_OPEN_CLICKOUTSIDE="WATCHFACES_OPEN_CLICKOUTSIDE"
    const val WATCHFACES_OPEN_SWIPEDOWN="WATCHFACES_OPEN_SWIPEDOWN"
    const val WATCHFACES_OPEN_BACK="WATCHFACES_OPEN_BACK"
    const val WATCHFACES_OPEN_UPLOAD="WATCHFACES_OPEN_UPLOAD"
    const val WATCHFACES_OPEN_FAVOURITES_ADD="WATCHFACES_OPEN_FAVOURITES_ADD"
    const val WATCHFACES_OPEN_FAVOURITES_REMOVE="WATCHFACES_OPEN_FAVOURITES_REMOVE"
    const val WATCHFACES_CATEGORY_OPEN="WATCHFACES_CATEGORY_OPEN"
    const val WATCHFACES_CATEGORY_OPEN_CLICKOUTSIDE="WATCHFACES_CATEGORY_OPEN_CLICKOUTSIDE"
    const val WATCHFACES_CATEGORY_OPEN_SWIPEDOWN="WATCHFACES_CATEGORY_OPEN_SWIPEDOWN"
    const val WATCHFACES_CATEGORY_OPEN_BACK="WATCHFACES_CATEGORY_OPEN_BACK"
    const val WATCHFACES_CATEGORY_OPEN_UPLOAD="WATCHFACES_CATEGORY_OPEN_UPLOAD"
    const val WATCHFACES_CATEGORY_OPEN_FAVOURITES_ADD="WATCHFACES_CATEGORY_OPEN_FAVOURITES_ADD"
    const val WATCHFACES_CATEGORY_OPEN_FAVOURITES_REMOVE="WATCHFACES_CATEGORY_OPEN_FAVOURITES_REMOVE"
    const val WATCHFACES_CATEGORY_CHANGECATEGORY="WATCHFACES_CATEGORY_CHANGECATEGORY"
    const val WATCHFACES_CATEGORY_MYFAVOURITES="WATCHFACES_CATEGORY_MYFAVOURITES"
    const val WATCHFACES_CATEGORY_MYFAVOURITES_REMOVE="WATCHFACES_CATEGORY_MYFAVOURITES_REMOVE"
    const val WATCHFACES_RATING="WATCHFACES_RATING_"
    const val WATCHFACES_RATING_CLEAR="WATCHFACES_RATING_CLEAR"
    const val WATCHFACES_RATING_SUBMIT="WATCHFACES_RATING_SUBMIT"
    const val WATCHFACES_RATING_NOTHANKYOU="WATCHFACES_RATING_NOTHANKYOU"
    const val WATCHFACES_RATING_SWIPE_DOWN="WATCHFACES_RATING_SWIPE_DOWN"
    const val WATCHFACES_RATING_CLICKOUTSIDE="WATCHFACES_RATING_CLICKOUTSIDE"
    const val WATCHFACES_RATING_BACK="WATCHFACES_RATING_BACK"
    const val WATCHFACES_CATEGORY_RATING="WATCHFACES_CATEGORY_RATING_"
    const val WATCHFACES_CATEGORY_RATING_CLEAR="WATCHFACES_CATEGORY_RATING_CLEAR"
    const val WATCHFACES_CATEGORY_RATING_SUBMIT="WATCHFACES_CATEGORY_RATING_SUBMIT"
    const val WATCHFACES_CATEGORY_RATING_NOTHANKYOU="WATCHFACES_CATEGORY_RATING_NOTHANKYOU"
    const val WATCHFACES_CATEGORY_RATING_SWIPE_DOWN="WATCHFACES_CATEGORY_RATING_SWIPE_DOWN"
    const val WATCHFACES_CATEGORY_RATING_CLICKOUTSIDE="WATCHFACES_CATEGORY_RATING_CLICKOUTSIDE"
    const val WATCHFACES_CATEGORY_RATING_BACK="WATCHFACES_CATEGORY_RATING_BACK"
    const val WATCHFACES_TRANSFER="WATCHFACES_TRANSFER"





}