package com.noisefit_commans.utils

object MoEngageLunaAppEvents {

    /**
     * Sleep Events ===============
     */
    const val aichat_initiated_clicked = "aichat_initiated_clicked"
    const val info_clicked = "info_clicked"
    const val day_selected = "day_selected"
    const val calender_day_selected = "calender_day_selected"
    const val calender_clicked = "calender_clicked"
    const val contributors_clicked = "contributors_clicked"
    const val trend_clicked = "trend_clicked"
    const val health_monitor_clicked = "health_monitor_clicked"
    const val health_monitor_temp_dev_selected = "health_monitor_temp_dev_selected"
    const val health_monitor_temp_abs_selected = "health_monitor_temp_abs_selected"
    const val article_clicked = "article_clicked"
    const val health_monitor_interval_change = "health_monitor_interval_change"
    const val contributors_interval_change = "contributors_interval_change"
    const val trend_interval_change = "trend_interval_change"
    const val contributors_calen_change_click = "contributors_calen_change_click"
    const val trend_calen_change_click = "trend_calen_change_click"
    const val health_monitor_calen_change_click = "health_monitor_calen_change_click"
    const val drop_down_selected = "drop_down_selected"
    /**
     * Sleep Events end ===============
     */

    /**
     * Readiness Events =============================
     */
    const val score_interval_change = "score_interval_change"
    const val score_clicked = "score_clicked"
    const val readiness_trend_clicked = "readiness_trend_clicked"
    /**
     * Readiness Events end ================================
     */


    /**
     * Activity Events =============================
     */
    const val activity_analysis_clicked = "readiness_trend_clicked"
    const val contributor_clicked = "contributor_clicked"
    const val workout_selected = "workout_selected"
    const val workout_add_button_clicked = "workout_add_button_clicked"
    const val past_workout_started = "past_workout_started"
    const val live_workout_started = "live_workout_started"
    const val live_workout_selection = "live_workout_selection"
    const val past_workout_entry = "past_workout_entry"
    const val workout_clicked = "workout_clicked"


    /**
     * Activity Events End=============================
     */




    /**
     * AI Events start =========================
     */
    const val home_footer_lunaai = "home_footer_lunaai"
    const val home_lunaai_daily_digest_plan = "home_lunaai_daily_digest_plan"
    const val home_lunaai_workout_plan = "home_lunaai_workout_plan"
    const val home_lunaai_nutrition_plan = "home_lunaai_nutrition_plan"
    const val Home_lunaai_suggested_question = "home_lunaai_suggested_question"
    const val Home_lunaai_mic_button = "home_lunaai_mic_button"

    /**
     * AI Events End =========================
     */

    const val luna_homepage_visit = "luna_homepage_visit"
    const val luna_activity_sync_manual = "luna_activity_sync_manual"
    const val luna_hamburger_click = "luna_hamburger_click"
    const val luna_your_profile_click = "luna_your_profile_click"
    const val luna_profile_edit_click = "luna_profile_edit_click"
    const val luna_profile_save_click = "luna_profile_save_click"
    const val luna_profile_name_edit_click = "luna_profile_name_edit_click"
    const val luna_profile_gender_edit_click = "luna_profile_gender_edit_click"
    const val luna_profile_dob_edit_click = "luna_profile_dob_edit_click"
    const val luna_profile_height_edit_click = "luna_profile_height_edit_click"
    const val luna_profile_weight_edit_click = "luna_profile_weight_edit_click"
    const val luna_help_support_click = "luna_help_support_click"
    const val luna_support_option_click = "luna_support_option_click"
    const val luna_support_options_question_click = "luna_support_options_question_click"
    const val luna_rate_us_click = "luna_rate_us_click"
    const val luna_rateus_rating = "luna_rateus_rating"
    const val luna_rateus_feedback = "luna_rateus_feedback"
    const val luna_rateus_submit_click = "luna_rateus_submit_click"
    const val luna_about_click = "luna_about_click"
    const val luna_about_terms_conditions_click = "luna_about_terms_conditions_click"
    const val luna_about_privacy_policy_click = "luna_about_privacy_policy_click"
    const val luna_about_check_update_click = "luna_about_check_update_click"
    const val luna_hamburger_logout_click = "luna_hamburger_logout_click"
    const val luna_device_capsule_click = "luna_device_capsule_click"
    const val luna_footer_mydevice_click = "luna_footer_mydevice_click"
    const val luna_footer_home_click = "luna_footer_home_click"
    const val luna_footer_sleep_click = "luna_footer_sleep_click"
    const val luna_footer_readiness_click = "luna_footer_readiness_click"
    const val luna_footer_activity_click = "luna_footer_activity_click"
    const val luna_mydevices_logs_click = "luna_mydevices_logs_click"
    const val luna_mydevices_share_logs_click = "luna_mydevices_share_logs_click"
    const val luna_mydevices_about_click = "luna_mydevices_about_click"
    const val luna_aboutdevice_copy_mac_click = "luna_aboutdevice_copy_mac_click"
    const val luna_aboutdevice_update_click = "luna_aboutdevice_update_click"
    const val luna_mydevices_unpair_click = "luna_mydevices_unpair_click"
    const val luna_homepage_activity_click = "luna_homepage_activity_click"
    const val luna_homepage_sleep_click = "luna_homepage_sleep_click"
    const val luna_homepage_readiness_click = "luna_homepage_readiness_click"
    const val luna_homepage_hr_refresh_click = "luna_homepage_hr_refresh_click"
    const val luna_homepage_sleep_score_click = "luna_homepage_sleep_score_click"
    const val luna_homepage_activity_score_click = "luna_homepage_activity_score_click"
    const val luna_homepage_readiness_score_click = "luna_homepage_readiness_score_click"
    const val luna_homepage_workouts_entry_click = "luna_homepage_workouts_entry_click"
    const val luna_workout_list_page_visit = "luna_workout_list_page_visit"
    const val luna_homepage_add_workout_click = "luna_homepage_add_workout_click"
    const val luna_add_workout = "luna_add_workout"
    const val luna_add_workout_start_time_click = "luna_add_workout_start_time_click"
    const val luna_add_workout_end_time_click = "luna_add_workout_end_time_click"
    const val luna_add_workout_intensity_click = "luna_add_workout_intensity_click"
    const val luna_workout = "luna_workout"
    const val luna_add_workout_save_click = "luna_add_workout_save_click"
    const val luna_sleep_page_visit = "luna_sleep_page_visit"
    const val luna_readiness_page_visit = "luna_readiness_page_visit"
    const val luna_activity_page_visit = "luna_activity_page_visit"
    const val luna_sleep_sleep_score_click = "luna_sleep_sleep_score_click"
    const val luna_sleep_total_sleep_click = "luna_sleep_total_sleep_click"
    const val luna_sleep_bed_time_click = "luna_sleep_bed_time_click"
    const val luna_sleep_sleep_efficiency_click = "luna_sleep_sleep_efficiency_click"
    const val luna_sleep_resting_hr_click = "luna_sleep_resting_hr_click"
    const val luna_sleep_stage_analysis_expand_click = "luna_sleep_stage_analysis_expand_click"
    const val luna_sleep_stage_analysis_compress_click = "luna_sleep_stage_analysis_compress_click"
    const val luna_sleep_date_range_click = "luna_sleep_date_range_click"
    const val luna_readiness_readiness_score_click = "luna_readiness_readiness_score_click"
    const val luna_readiness_resting_hr_click = "luna_readiness_resting_hr_click"
    const val luna_readiness_hr_variability_click = "luna_readiness_hr_variability_click"
    const val luna_readiness_body_temp_click = "luna_readiness_body_temp_click"
    const val luna_readiness_respiratory_rate_click = "luna_readiness_respiratory_rate_click"
    const val luna_readiness_date_range_click = "luna_readiness_date_range_click"
    const val luna_activity_activity_score_click = "luna_activity_activity_score_click"
    const val luna_activity_goal_progress_click = "luna_activity_goal_progress_click"
    const val luna_activity_total_calories_click = "luna_activity_total_calories_click"
    const val luna_activity_distance_click = "luna_activity_distance_click"
    const val day_click = "day_click"
    const val week_click = "week_click"
    const val month_click = "month_click"
    const val info_click = "info_click"
    const val luna_welcome_page_continue_button_click = "luna_welcome_page_continue_button_click"
    const val luna_land_on_start_fitness_page_visit = "luna_land_on_start_fitness_page_visit"
    const val luna_sign_in_google = "luna_sign_in_google"
    const val luna_sign_in_apple = "luna_sign_in_apple"//will applicable for iOS only
    const val luna_sign_in_email = "luna_sign_in_email"
    const val luna_land_on_enter_phone_no_page_visit = "luna_land_on_enter_phone_no_page_visit"
    const val luna_land_on_enter_otp_page_visit = "luna_land_on_enter_otp_page_visit"
    const val luna_land_on_look_for_device_page_visit = "luna_land_on_look_for_device_page_visit"
    const val luna_registration_device_selected = "luna_registration_device_selected"
    const val luna_successful_registration_done = "luna_successful_registration_done"
    const val luna_land_on_set_up_profile_page_visit = "luna_land_on_set_up_profile_page_visit"
    const val luna_land_on_enter_name_page = "luna_land_on_enter_name_page"
    const val luna_land_on_enter_age_page_visit = "luna_land_on_enter_age_page_visit"
    const val luna_land_on_enter_gender_page_visit = "luna_land_on_enter_gender_page_visit"
    const val luna_gender_select_click = "luna_gender_select_click"
    const val luna_land_on_enter_weight_page_visit = "luna_land_on_enter_weight_page_visit"
    const val luna_land_on_enter_height_page_visit = "luna_land_on_enter_height_page_visit"
    const val luna_land_on_daily_goal_set_page_visit = "luna_land_on_daily_goal_set_page_visit"
    const val luna_profile_successful_setup = "luna_profile_successful_setup"

    const val luna_body_temp_page_visit = "luna_body_temp_page_visit"
    const val luna_body_temp_info_click = "luna_body_temp_info_click"
    const val luna_mydevice_wt_got_it_click = "luna_mydevice_wt_got_it_click"
    const val luna_activity_add_click = "luna_activity_add_click"
    const val luna_homepage_mydevice_click = "luna_homepage_mydevice_click"
    const val luna_activity_record_workout_click = "luna_activity_record_workout_click"
    const val luna_preworkout_connection_prompt = "luna_preworkout_connection_prompt"
    const val luna_preworkout_connection_done_click = "luna_preworkout_connection_done_click"
    const val luna_preworkout_charge_alert_done_click = "luna_preworkout_charge_alert_done_click"
    const val luna_preworkout_disconnected_try_click = "luna_preworkout_disconnected_try_click"
    const val luna_preworkout_bluetooth_done_click = "luna_preworkout_bluetooth_done_click"
    const val luna_workout_list_select_click = "luna_workout_list_select_click"
    const val luna_workout_list_done_click = "luna_workout_list_done_click"
    const val luna_record_workout_start_click = "luna_record_workout_start_click"
    const val luna_record_workout_pause_click = "luna_record_workout_pause_click"
    const val luna_record_workout_end_click = "luna_record_workout_end_click"
    const val luna_record_workout_end_delete_click = "luna_record_workout_end_delete_click"
    const val luna_record_workout_end_save_click = "luna_record_workout_end_save_click"
    const val luna_workout_detail_page_visit = "luna_workout_detail_page_visit"
    const val luna_workout_detail_page_edit_click = "luna_workout_detail_page_edit_click"
    const val luna_workout_detail_page_delete_click = "luna_workout_detail_page_delete_click"
    const val luna_homepage_alert_click = "luna_homepage_alert_click"
    const val luna_homepage_welcome_card_click = "luna_homepage_welcome_card_click"
    const val luna_homepage_ring_care_card_click = "luna_homepage_ring_care_card_click"
    const val luna_homepage_readiness_info_card_click = "luna_homepage_readiness_info_card_click"
    const val luna_homepage_readiness_track_card_click = "luna_homepage_readiness_track_card_click"
    const val luna_homepage_sleep_info_card_click = "luna_homepage_sleep_info_card_click"
    const val luna_sleep_page_get_started_click = "luna_sleep_page_get_started_click"
    const val luna_readiness_page_get_started_click = "luna_readiness_page_get_started_click"
    const val luna_activity_page_get_started_click = "luna_activity_page_get_started_click"
    const val luna_readiness_page_hr_info_click = "luna_readiness_page_hr_info_click"
    const val luna_readiness_page_hrv_info_click = "luna_readiness_page_hrv_info_click"
    const val luna_readiness_page_temp_info_click = "luna_readiness_page_temp_info_click"
    const val luna_activity_page_dtm_info_click = "luna_activity_page_dtm_info_click"
    const val luna_sleep_page_hr_info_click = "luna_sleep_page_hr_info_click"
    const val luna_sleep_page_hrv_info_click = "luna_sleep_page_hrv_info_click"
    const val luna_media_player_play_click = "luna_media_player_play_click"
    const val luna_media_player_pause_click = "luna_media_player_pause_click"
    const val luna_mydevices_settings_click = "luna_mydevices_settings_click"
    const val luna_learnmore_click = "luna_learnmore_click"
    const val luna_learnmore_card_click = "luna_learnmore_card_click"
    const val luna_myprofile_page_delete_account_click = "luna_myprofile_page_delete_account_click"
    const val luna_activity_page_enable_gfit_click = "luna_activity_page_enable_gfit_click"
    const val luna_activity_page_enable_ahealth_click = "luna_activity_page_enable_ahealth_click"
    const val luna_activity_page_workout_added_click = "luna_activity_page_workout_added_click"
    const val luna_device_settings_restart_click = "luna_device_settings_restart_click"
    const val luna_device_settings_reset_click = "luna_device_settings_reset_click"
    const val luna_device_settings_pair_ring_click = "luna_device_settings_pair_ring_click"
    const val luna_device_settings_reset_confirm_click = "luna_device_settings_reset_confirm_click"
    const val luna_device_settings_reset_cancel_click = "luna_device_settings_reset_cancel_click"
    const val luna_myprofile_logout_allow_click = "luna_myprofile_logout_allow_click"
    const val luna_myprofile_logout_cancel_click = "luna_myprofile_logout_cancel_click"
    const val luna_myprofile_delete_allow_click = "luna_myprofile_delete_allow_click"
    const val luna_myprofile_delete_cancel_click = "luna_myprofile_delete_cancel_click"
    const val luna_add_workout_record_click = "luna_add_workout_record_click"
    const val luna_add_workout_add_click = "luna_add_workout_add_click"
    const val luna_homepage_workout_item_click = "luna_homepage_workout_item_click"

    const val luna_sleep_cues_view = "luna_sleep_cues_view"
    const val luna_sleep_nightmovement_info_click = "luna_sleep_nightmovement_info_click"
    const val luna_sleep_contributor = "luna_sleep_contributor"
    const val luna_sleep_contributor_duration_click = "luna_sleep_contributor_duration_click"
    const val luna_sleep_contributor_efficiency_click = "luna_sleep_contributor_efficiency_click"
    const val luna_sleep_contributor_restfulness_click = "luna_sleep_contributor_restfulness_click"
    const val luna_sleep_contributor_remsleep_click = "luna_sleep_contributor_remsleep_click"
    const val luna_sleep_contributor_deepsleep_click = "luna_sleep_contributor_deepsleep_click"
    const val luna_sleep_contributor_latency_click = "luna_sleep_contributor_latency_click"
    const val luna_sleep_contributor_timing_click = "luna_sleep_contributor_timing_click"
    const val luna_sleep_contributor_spo2_click = "luna_sleep_contributor_spo2_click"
    const val luna_sleep_contributor_heartrate_click = "luna_sleep_contributor_heartrate_click"
    const val luna_sleep_contributor_hrv_click = "luna_sleep_contributor_hrv_click"

    const val luna_readiness_skin_temp_click = "luna_readiness_skin_temp_click"
    const val luna_readiness_contributor = "luna_readiness_contrib"
    const val luna_readiness_contrib_sscore_click = "luna_readiness_contrib_sscore_click"
    const val luna_readiness_contrib_activity_click = "luna_readiness_contrib_activity_click"
    const val luna_readiness_contrib_recovery_click = "luna_readiness_contrib_recovery_click"
    const val luna_readiness_contrib_regularity_click = "luna_readiness_contrib_regularity_click"
    const val luna_readiness_contrib_sbalance_click = "luna_readiness_contrib_sbalance_click"
    const val luna_readiness_contrib_heartrate_click = "luna_readiness_contrib_heartrate_click"
    const val luna_readiness_contrib_abalance_click = "luna_readiness_contrib_abalance_click"
    const val luna_readiness_contrib_hrv_balance_click = "luna_readiness_contrib_hrv_balance_click"
    const val luna_readiness_contrib_skin_temp_click = "luna_readiness_contrib_skin_temp_click"
    const val luna_readiness_heart_rate_info_click = "luna_readiness_heart_rate_info_click"
    const val luna_readiness_hrv_info_click = "luna_readiness_hrv_info_click"

    const val luna_activity_steps_click = "luna_activity_steps_click"
    const val luna_activity_contributor = "luna_activity_contributor"
    const val luna_activity_contributors_stay_click = "luna_activity_contributors_stay_click"
    const val luna_activity_contributors_move_click = "luna_activity_contributors_move_click"
    const val luna_activity_contributors_calorie_click = "luna_activity_contributors_calorie_click"
    const val luna_activity_contributors_tfreq_click = "luna_activity_contributors_tfreq_click"
    const val luna_activity_contributors_tvol_click = "luna_activity_contributors_tvol_click"
    const val luna_activity_movement_info_click = "luna_activity_movement_info_click"
    const val luna_activity_workouts_viewall_click = "luna_activity_workouts_viewall_click"
    const val luna_activity_workouts_item_click = "luna_activity_workouts_item_click"
    const val luna_activity_add_workout_click = "luna_activity_add_workout_click"
    const val luna_activity_add_workout_add_click = "luna_activity_add_workout_add_click"
    const val luna_activity_add_workout_record_click = "luna_activity_add_workout_record_click"

    const val sleep_recorded = "sleep_recorded"
    const val luna_homepage_low_battery_click = "luna_homepage_low_battery_click"
    const val luna_homepage_stress_click = "luna_homepage_stress_click"
    const val luna_stress_visit = "luna_stress_visit"
    const val luna_stress_movement_down_click = "luna_stress_movement_down_click"
    const val luna_stress_movement_click = "luna_stress_movement_click"
    const val luna_overall_stress_click = "luna_overall_stress_click"
    const val luna_non_active_stress_click = "luna_non_active_stress_click"
    const val luna_how_it_works_stress_click = "luna_how_it_works_stress_click"
    const val luna_overall_stress_page_visit = "luna_overall_stress_page_visit"
    const val luna_non_active_stress_page_visit = "luna_non_active_stress_page_visit"
    const val luna_stress_i_button_click = "luna_stress_i_button_click"
    const val luna_stress_i_page_visit = "luna_stress_i_page_visit"

    const val luna_cycle_tracking_page_visit = "luna_cycle_tracking_page_visit"
    const val luna_cycle_tracking_calendar_button_click = "luna_cycle_tracking_calendar_button_click"
    const val luna_cycle_temperature_page_visit = "luna_cycle_temperature_page_visit"
    const val luna_cycle_cycle_length_page_visit = "luna_cycle_cycle_length_page_visit"
    const val luna_cycle_period_duration_page_visit = "luna_cycle_period_duration_page_visit"
    const val luna_cycle_cycle_history_page_visit = "luna_cycle_cycle_history_page_visit"
    const val luna_cycle_i_phase_page_visit = "luna_cycle_i_phase_page_visit"
    const val luna_cycle_i_page_visit = "luna_cycle_i_page_visit"
    const val luna_cycle_i_temperature_visit = "luna_cycle_i_temperature_visit"
    const val luna_cycle_log_button_click = "luna_cycle_log_button_click"
    const val luna_cycle_log_period_click = "luna_cycle_log_period_click"
    const val luna_cycle_log_flow_click = "luna_cycle_log_flow_click"
    const val luna_cycle_log_symtoms_click = "luna_cycle_log_symtoms_click"
    const val luna_cycle_log_period_calendar_view = "luna_cycle_log_period_calendar_view"
    const val luna_cycle_log_period_calendar_save_click = "luna_cycle_log_period_calendar_save_click"
    const val luna_cycle_save_click = "luna_cycle_save_click"
    const val luna_ai_page_visit = "luna_ai_page_visit"
    const val luna_ai_message_submit = "luna_ai_message_submit"


}