apply {
    from("$rootDir/android-library-build.gradle")
}



dependencies {

    implementation project(":noisefit_libraries_zh")


    //def timber = "4.7.1"

    implementation fileTree(dir: "libs", include: ["*.jar"])


    implementation libs.protobuf
    implementation libs.androidx.localbroadcastmanager

    //utils
    implementation libs.utilcodex.v1311

    implementation (project(Modules.commons))
//    implementation project(path: ':commons')


}

android {
    namespace 'com.noisefit_zhsdk'
}